package io.kotgent.store

import app.cash.sqldelight.db.AfterVersion
import app.cash.sqldelight.db.QueryResult
import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.db.SqlSchema
import app.cash.sqldelight.driver.native.inMemoryDriver
import io.kotgent.db.KotgentDatabase
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Storage spike (Task 4) — SQLDelight on the Kotlin Toolchain.
 *
 * SQLDelight normally ships a Gradle plugin for code generation, which the Kotlin Toolchain
 * cannot consume. The spike proves we can KEEP SQLDelight by (a) driving SQLDelight's compiler
 * from our own `jvm/amper-plugin` (see plugins/sqldelight-gen) to generate typed Kotlin from a
 * `.sq` file, and (b) running that generated code against SQLDelight's `native-driver` on
 * macosArm64.
 *
 * [nativeDriverRawRoundTrip] is the RUNTIME half of the spike (risk gate 1): it proves the
 * third-party `native-driver` klib resolves for macosArm64, LINKS into the test binary (KT-78062
 * only bites our own raw cinterop, not dependency klibs — see WsSpikeTest), and executes a real
 * in-memory SQLite insert/select round-trip via its sqliter cinterop. It uses raw SQL so it is
 * independent of the codegen half.
 *
 * [generatedApiRoundTrip] is the CODEGEN half: it uses the Kotlin API generated by our plugin
 * from `sqldelight/io/kotgent/db/Spike.sq`, proving the full pipeline (`.sq` -> plugin codegen ->
 * compiled into the native module -> runtime round-trip).
 *
 * Every DB interaction is wrapped in a bounded [withTimeout] (anti-flaky, mirrors PtyTest/WsSpikeTest).
 */
class SqlDelightSpikeTest {

    /** A trivial schema created directly via raw DDL — no generated code involved. */
    private val rawSchema = object : SqlSchema<QueryResult.Value<Unit>> {
        override val version: Long = 1
        override fun create(driver: SqlDriver): QueryResult.Value<Unit> {
            driver.execute(null, "CREATE TABLE spike(id INTEGER PRIMARY KEY, value TEXT NOT NULL)", 0)
            return QueryResult.Unit
        }
        override fun migrate(
            driver: SqlDriver,
            oldVersion: Long,
            newVersion: Long,
            vararg callbacks: AfterVersion,
        ): QueryResult.Value<Unit> = QueryResult.Unit
    }

    @Test
    fun nativeDriverRawRoundTrip() = runBlocking {
        withTimeout(20_000) {
            val driver = inMemoryDriver(rawSchema)
            try {
                driver.execute(null, "INSERT INTO spike(value) VALUES ('hello-native-driver')", 0).value
                val read = driver.executeQuery(
                    identifier = null,
                    sql = "SELECT value FROM spike LIMIT 1",
                    mapper = { cursor ->
                        check(cursor.next().value) { "expected at least one row" }
                        QueryResult.Value(cursor.getString(0))
                    },
                    parameters = 0,
                ).value
                assertEquals("hello-native-driver", read, "native-driver insert/select round-trip")
            } finally {
                driver.close()
            }
        }
    }

    @Test
    fun generatedApiRoundTrip() = runBlocking {
        // The full spike acceptance: KotgentDatabase / SpikeQueries / KotgentDatabase.Schema are
        // generated by the sqldelight-gen plugin from sqldelight/io/kotgent/db/Spike.sq at build
        // time (no hand-written SQL here). Driving that TYPED, generated API against native-driver
        // proves the whole pipeline: `.sq` -> plugin codegen -> compiled into the macosArm64 module
        // -> runtime insert/select round-trip.
        withTimeout(20_000) {
            val driver = inMemoryDriver(KotgentDatabase.Schema)
            try {
                val db = KotgentDatabase(driver)
                db.spikeQueries.insertValue("hello-sqldelight")
                val latest = db.spikeQueries.selectLatest().executeAsOne()
                assertEquals("hello-sqldelight", latest, "generated SQLDelight insert/select round-trip")
            } finally {
                driver.close()
            }
        }
    }
}
