package io.kotgent.buildinfo

import org.jetbrains.amper.plugins.ExecutionAvoidance
import org.jetbrains.amper.plugins.Input
import org.jetbrains.amper.plugins.Output
import org.jetbrains.amper.plugins.TaskAction
import java.io.IOException
import java.nio.file.Path

/**
 * Generates the immutable version metadata compiled into the native application.
 *
 * Execution avoidance is intentionally disabled. In a linked Git worktree, `.git` is a stable text
 * file while the branch ref that changes on every commit lives in the common Git directory outside
 * this project tree. No honest finite `@Input` path inside the worktree therefore tracks HEAD.
 */
@TaskAction(executionAvoidance = ExecutionAvoidance.Disabled)
fun generateBuildInfo(
    @Input versionFile: Path,
    @Output generatedSourceDir: Path,
) {
    val version = readVersion(versionFile)
    val releaseBuild = releaseBuildFrom(System.getenv(RELEASE_BUILD_ENV))
    val gitHash = if (releaseBuild) "" else readGitHash(versionFile.parent)

    val outputRoot = generatedSourceDir.toFile()
    outputRoot.deleteRecursively()
    val outputFile = outputRoot.resolve("io/kotgent/GeneratedBuildInfo.kt")
    check(outputFile.parentFile.mkdirs() || outputFile.parentFile.isDirectory) {
        "cannot create generated build-info directory: ${outputFile.parent}"
    }
    outputFile.writeText(generatedBuildInfoSource(version, gitHash, releaseBuild))
}

private const val RELEASE_BUILD_ENV: String = "KOTGENT_RELEASE_BUILD"

private val VERSION_PATTERN =
    Regex("""[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?""")
private val GIT_HASH_PATTERN = Regex("[0-9a-f]{7,64}")

internal fun readVersion(versionFile: Path): String {
    val version = versionFile.toFile().readText().trim()
    require(version.matches(VERSION_PATTERN)) {
        "$versionFile must contain one semantic version, got ${kotlinStringLiteral(version)}"
    }
    return version
}

/** Unset means an ordinary source build; a set flag must be explicit to avoid a hashed release. */
fun releaseBuildFrom(raw: String?): Boolean = when (raw) {
    null -> false
    "true" -> true
    else -> error("$RELEASE_BUILD_ENV must be exactly 'true' when set, got ${kotlinStringLiteral(raw)}")
}

private fun readGitHash(projectRoot: Path): String {
    val process = try {
        ProcessBuilder("git", "-C", projectRoot.toString(), "rev-parse", "--short=7", "HEAD")
            .redirectErrorStream(true)
            .start()
    } catch (e: IOException) {
        warnAboutMissingGitHash("cannot run git: ${e.message}")
        return ""
    }

    val output = process.inputStream.bufferedReader().use { it.readText() }
    val exitCode = process.waitFor()
    if (exitCode != 0) {
        warnAboutMissingGitHash("git rev-parse failed with exit $exitCode: ${output.trim().take(500)}")
        return ""
    }

    val hash = output.trim().lowercase()
    if (!hash.matches(GIT_HASH_PATTERN)) {
        warnAboutMissingGitHash("git rev-parse returned an invalid short hash: ${kotlinStringLiteral(hash)}")
        return ""
    }
    return hash
}

private fun warnAboutMissingGitHash(reason: String) {
    System.err.println("[build-info] warning: $reason; the UI will show VERSION only")
}

fun generatedBuildInfoSource(
    version: String,
    gitHash: String,
    releaseBuild: Boolean,
): String = """
    // Generated by plugins/build-info. Do not edit.
    package io.kotgent

    public const val VERSION: String = ${kotlinStringLiteral(version)}
    internal const val BUILD_GIT_HASH: String = ${kotlinStringLiteral(gitHash)}
    internal const val BUILD_IS_RELEASE: Boolean = $releaseBuild
    """.trimIndent() + "\n"

/**
 * Quotes arbitrary text as a regular Kotlin string literal.
 *
 * Version/hash validation already limits production values, but escaping at the code-generation
 * boundary prevents a future input expansion from producing invalid or injectable Kotlin source.
 */
fun kotlinStringLiteral(value: String): String = buildString(value.length + 2) {
    append('"')
    for (char in value) {
        when (char) {
            '"' -> append("\\\"")
            '\\' -> append("\\\\")
            '$' -> {
                append('\\')
                append('$')
            }
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            '\b' -> append("\\b")
            else -> {
                val code = char.code
                if (code in 0x00..0x1f || code in 0x7f..0x9f || code == 0x2028 || code == 0x2029) {
                    append("\\u")
                    append(code.toString(16).padStart(4, '0'))
                } else {
                    append(char)
                }
            }
        }
    }
    append('"')
}
