package io.kotgent.adapter.claude

import io.kotgent.adapter.AgentAdapter
import io.kotgent.adapter.LaunchMode
import io.kotgent.adapter.LaunchSpec
import io.kotgent.core.AgentEvent
import io.kotgent.core.ProviderSessionId
import io.kotgent.core.newUuidV4
import kotlinx.coroutines.flow.Flow

/**
 * The Claude [AgentAdapter] (plan Task 11) — the OUTGOING side of the Claude integration:
 *
 *  - [buildLaunchSpec] renders the `claude` argv for a New or Resume launch. A [LaunchMode.New]
 *    preallocates a v4 UUID and passes it as `claude --session-id <uuid>` (version-gated, see below),
 *    surfacing it on [LaunchSpec.preallocatedSessionId] so the daemon can emit `SessionBound` up
 *    front instead of waiting on the `SessionStart` hook. A [LaunchMode.Resume] re-addresses the
 *    saved conversation with `claude --resume <id>`. Both install the hook config via
 *    `--settings <settingsPath>` (generated by [ClaudeHookConfig], written to disk by the daemon).
 *
 *  - [events] is an INJECTED seam. The Claude adapter's real events arrive via hook callbacks to the
 *    HTTP ingress + normalizer, which are Task 12. Here the stream is simply wired through from the
 *    constructor; Task 12 constructs the adapter with a `Channel`/`SharedFlow`-backed flow the ingress
 *    feeds. This adapter does NOT produce events itself. (Transcript watching is backlog.)
 *
 * ## Version gate
 * `--session-id` is confirmed in the installed 2.1.x claude. [sessionIdSupported] (computed once from
 * [ClaudeCli.supportsSessionId] and passed in) decides preallocation: when `false` (an older CLI, or
 * an unparseable version), [buildLaunchSpec] omits `--session-id` and preallocates nothing — the id
 * is captured later from the `SessionStart` hook (→ `SessionBound`).
 */
class ClaudeAdapter(
    /** Working directory the agent runs in (the session's `cwd`). */
    private val cwd: String,
    /** Path to the generated hook settings file, passed as `--settings <settingsPath>`. */
    private val settingsPath: String,
    /**
     * The normalized event stream, fed by Task 12's hook ingress + normalizer. Injected, not
     * produced here — the adapter only exposes it so downstream (reducer/store/transport) can fold it.
     */
    override val events: Flow<AgentEvent>,
    /**
     * Whether the target `claude` supports `--session-id` (from [ClaudeCli.supportsSessionId]).
     * Defaults to `true` (modern CLI); pass `false` to exercise the fallback path.
     */
    private val sessionIdSupported: Boolean = true,
    /** The claude program name / path used as argv[0]. */
    private val binaryName: String = "claude",
    /** Extra environment for the launch (kept minimal; `KOTGENT_SESSION_ID` is a tmux-side debug label). */
    private val env: Map<String, String> = emptyMap(),
    /** How a fresh provider session id is minted — injectable for deterministic tests. */
    private val generateSessionId: () -> ProviderSessionId = { ProviderSessionId(newUuidV4()) },
    /** Detected `claude` version (e.g. `"2.1.218"`), echoed onto every [LaunchSpec.cliVersion]. */
    private val cliVersion: String? = null,
    /** Resolved `claude` path, echoed onto every [LaunchSpec.cliPath]. */
    private val cliPath: String? = null,
) : AgentAdapter {

    override fun buildLaunchSpec(mode: LaunchMode): LaunchSpec = when (mode) {
        is LaunchMode.New ->
            if (sessionIdSupported) {
                val id = generateSessionId()
                LaunchSpec(
                    command = listOf(binaryName, "--session-id", id.value, "--settings", settingsPath),
                    env = env,
                    cwd = cwd,
                    preallocatedSessionId = id,
                    cliVersion = cliVersion,
                    cliPath = cliPath,
                )
            } else {
                // Fallback for pre-`--session-id` CLIs: no preallocation; the id is captured from the
                // SessionStart hook (→ SessionBound). Hook settings are still installed.
                LaunchSpec(
                    command = listOf(binaryName, "--settings", settingsPath),
                    env = env,
                    cwd = cwd,
                    preallocatedSessionId = null,
                    cliVersion = cliVersion,
                    cliPath = cliPath,
                )
            }

        is LaunchMode.Resume ->
            LaunchSpec(
                command = listOf(binaryName, "--resume", mode.providerSessionId.value, "--settings", settingsPath),
                env = env,
                cwd = cwd,
                preallocatedSessionId = null,
                cliVersion = cliVersion,
                cliPath = cliPath,
            )
    }
}
