package io.kotgent.tmux

/**
 * Generates the private session-close hook. The token stays in a `0600` header file, loopback requests
 * are bounded against orphan-held sockets, and absolute curl avoids launchd PATH dependence.
 */
object TmuxHookConfig {
    const val INGRESS_PATH: String = "/api/v1/hooks/tmux"

    const val LEGACY_INGRESS_PATH: String = "/hooks/tmux"

    const val HOOK_TOKEN_HEADER: String = "X-Kotgent-Hook-Token"

    const val SESSION_HEADER: String = "X-Kotgent-Tmux-Session"

    const val CURL_PATH: String = "/usr/bin/curl"

    const val CURL_CONNECT_TIMEOUT_SECONDS: Int = 2

    const val CURL_MAX_TIME_SECONDS: Int = 5

    fun ingressUrl(port: Int): String = "http://127.0.0.1:$port$INGRESS_PATH"

    fun headerFileContent(token: String): String = "$HOOK_TOKEN_HEADER: $token\n"

    fun hookScript(port: Int, headerFilePath: String): String = buildString {
        appendLine("#!/bin/sh")
        appendLine("# Generated by kotgent — do not edit. Invoked by tmux as: <script> <session-name>")
        appendLine("exec $CURL_PATH -sS -o /dev/null -X POST \\")
        appendLine("  --connect-timeout $CURL_CONNECT_TIMEOUT_SECONDS --max-time $CURL_MAX_TIME_SECONDS \\")
        appendLine("  -H ${shSingleQuote("@$headerFilePath")} \\")
        // The session name must expand when tmux invokes the hook.
        appendLine("  -H \"$SESSION_HEADER: \$1\" \\")
        appendLine("  --data '' \\")
        appendLine("  ${shSingleQuote(ingressUrl(port))}")
    }

    /**
     * Tmux's `q:` modifier shell-quotes user-created session names before substitution into run-shell.
     */
    fun hookCommand(scriptPath: String): String =
        "run-shell \"/bin/sh ${shSingleQuote(scriptPath)} '#{q:hook_session_name}'\""

    private fun shSingleQuote(value: String): String = "'" + value.replace("'", "'\\''") + "'"
}
