package io.kotgent.tmux

/**
 * Pure generation of the private artifacts that connect tmux's global `session-closed` hook to the
 * daemon: a small `/bin/sh` script ([hookScript]), its curl-compatible token header
 * ([headerFileContent]), and the command installed into tmux ([hookCommand]). The daemon writes the
 * script and header file mode `0600`; naming `/bin/sh` explicitly means the script needs no execute bit.
 *
 * The token lives only in the header file and curl reads it with `-H @<file>`, so it never appears in
 * the tmux server's hook command or a process argv. The HTTP request is strictly time-bounded. That is
 * mandatory even on loopback: a listening socket inherited by an orphan can accept a connection and
 * then stay silent forever, otherwise leaving an immortal curl process for every closed session.
 *
 * `/usr/bin/curl` is absolute for the same reason the VAPID signer pins `/usr/bin/openssl`: this daemon
 * edge must not depend on command lookup. It is deliberately not justified by a different `run-shell`
 * PATH — tmux special-cases PATH, so the hook inherits the same server snapshot as provider scripts.
 */
object TmuxHookConfig {

    /** The loopback-only ingress path that receives tmux close notifications. */
    const val INGRESS_PATH: String = "/hooks/tmux"

    /** Header carrying the shared hook token. */
    const val HOOK_TOKEN_HEADER: String = "X-Kotgent-Hook-Token"

    /** Header carrying the closed tmux session name (for example `kt-1a2b3c4d`). */
    const val SESSION_HEADER: String = "X-Kotgent-Tmux-Session"

    /** Absolute system curl used by the launchd/tmux edge; see the class KDoc. */
    const val CURL_PATH: String = "/usr/bin/curl"

    /** Bound establishing the loopback connection, in seconds. */
    const val CURL_CONNECT_TIMEOUT_SECONDS: Int = 2

    /** Bound on the complete hook request, in seconds. */
    const val CURL_MAX_TIME_SECONDS: Int = 5

    /** The ingress URL for the daemon's loopback [port]. */
    fun ingressUrl(port: Int): String = "http://127.0.0.1:$port$INGRESS_PATH"

    /** One newline-terminated header line for the private curl header file. */
    fun headerFileContent(token: String): String = "$HOOK_TOKEN_HEADER: $token\n"

    /**
     * The non-executable `/bin/sh` script tmux invokes with the closed session name as `$1`.
     * It sends an empty POST body, reads the token from [headerFilePath], and carries `$1` in
     * [SESSION_HEADER]. Both connection and total timeouts are load-bearing; see the class KDoc.
     */
    fun hookScript(port: Int, headerFilePath: String): String = buildString {
        appendLine("#!/bin/sh")
        appendLine("# Generated by kotgent — do not edit. Invoked by tmux as: <script> <session-name>")
        appendLine("exec $CURL_PATH -sS -o /dev/null -X POST \\")
        appendLine("  --connect-timeout $CURL_CONNECT_TIMEOUT_SECONDS --max-time $CURL_MAX_TIME_SECONDS \\")
        // The token is read from the 0600 header file, never embedded in this script or an argv.
        appendLine("  -H ${shSingleQuote("@$headerFilePath")} \\")
        // Double-quoted so the hook-time shell expands the session-name argument.
        appendLine("  -H \"$SESSION_HEADER: \$1\" \\")
        appendLine("  --data '' \\")
        appendLine("  ${shSingleQuote(ingressUrl(port))}")
    }

    /**
     * The exact tmux 3.7b-verified hook body: invoke [scriptPath] through `/bin/sh`, passing the
     * closing session's name. [scriptPath] is POSIX-single-quoted so it remains one literal word.
     * `#{q:hook_session_name}` is intentional rather than the bare format: tmux shell-quotes the
     * substituted name, so even a user-created session containing a quote cannot break out of the
     * generated `/bin/sh` command. The surrounding form was verified end-to-end on tmux 3.7b.
     */
    fun hookCommand(scriptPath: String): String =
        "run-shell \"/bin/sh ${shSingleQuote(scriptPath)} '#{q:hook_session_name}'\""

    /** Render [value] as one fully literal POSIX shell word. */
    private fun shSingleQuote(value: String): String = "'" + value.replace("'", "'\\''") + "'"
}
