import { render } from "preact";
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from "preact/hooks";
import { html } from "htm/preact";
// Importing the adapter installs Preact's options hooks, which is what makes a signal read in a render
// body subscribe the component that read it. Without this import `.value` still answers correctly and
// the tree simply never re-renders again, so the import is load-bearing even with nothing named here.
import "@preact/signals";

import {
  apiRequest,
  errorMessage,
  isDefiniteAnswer,
  isUnauthenticated,
  wsUrl,
} from "./lib/api.js";
import { writeClipboard } from "./lib/clipboard.js";
import {
  ABORT_PROBE,
  ATTACH,
  CANCEL_TIMER,
  HINT_CLEAR,
  HINT_DEAD,
  HINT_DETACHED,
  PROBE,
  SCHEDULE,
  cancel as cancelReattachEvent,
  grant as grantReattach,
  grantAndSchedule,
  hidden as pageHidden,
  initialReattachState,
  probeFailed,
  probeResolved,
  reduceReattach,
  sessionStateChanged,
  snapshotApplied,
  terminalClosed,
  timerFired,
} from "./lib/reattach.js";
import { createSerialRefresh } from "./lib/refresh.js";
import { affectsAttachment, buildCommands } from "./lib/commands.js";
import { MUTATION_BUSY_MESSAGE, pendingMutation, runMutation } from "./lib/mutation.js";
import { READY } from "./lib/readiness.js";
import {
  loadSidebarCollapsed,
  persistSidebarCollapsed,
} from "./lib/prefs.js";
import { notifyAttention } from "./lib/notify.js";
import {
  capitalize,
  displayName,
  isAliveState,
  sessionTaskLinkDisabledReason,
  sessionTaskLinkOutcome,
  sessionTaskLinkSubmitBlocked,
  stateBadge,
  tmuxAttachCommand,
} from "./lib/sessions.js";
import {
  SCREEN_SESSIONS,
  SCREEN_TASK,
  SCREEN_TASKS,
  navigate,
  parseRoute,
  routePath,
  sessionPath,
  subscribeToRoute,
  taskPath,
} from "./lib/router.js";
import {
  deleteProject,
  fetchProjects,
  linkTask,
  restoreProject,
} from "./lib/tasks.js";
import {
  findSession,
  mergeSessionPatch,
  mergeSessionRow,
  replaceSessions,
  sessions as sessionsSignal,
  sessionsReadiness,
} from "./state/sessions.js";
import {
  dropTask,
  findTask,
  mergeTaskPatch,
  mergeTaskRow,
  replaceTasks,
  tasks as tasksSignal,
  tasksReadiness,
} from "./state/tasks.js";
import {
  applyProjectRow,
  findProject,
  isLiveProject,
  projects as projectsSignal,
  projectsReadiness,
  removeProjectRow,
  replaceProjects,
} from "./state/projects.js";
import {
  activeSession as activeSessionSignal,
  activeSessionId,
  markSelection,
  pruneSelection,
  selectSessionId,
} from "./state/selection.js";
import {
  closeDialog,
  closeDialogFrom,
  dialog as dialogSignal,
  openDialog,
} from "./state/dialog.js";
import { announcementHolds, say, status as statusSignal } from "./state/status.js";
import { mergeUsageWindow, replaceUsage } from "./state/usage.js";
import {
  PREFS_SUPERSEDED,
  PREFS_UNREADABLE,
  applyDevicePreferences,
  applyServerPreferences,
  prefs as prefsSignal,
  serverPrefs,
} from "./state/prefs.js";
import { Board } from "./components/Board.js";
import { TaskDetail } from "./components/TaskDetail.js";
import { CommandPalette } from "./components/CommandPalette.js";
import { Sidebar } from "./components/Sidebar.js";
import { TerminalPane } from "./components/TerminalPane.js";
import {
  DeleteProjectDialog,
  HelpDialog,
  LinkTaskDialog,
  NewSessionDialog,
  PhoneDialog,
  PreferencesDialog,
  RenameSessionDialog,
  RestoreProjectDialog,
  UploadFilesDialog,
} from "./components/dialogs.js";

const SELECT_HINT = "Select a session on the left to attach its terminal.";
const REATTACH_LIVENESS_TIMEOUT_MS = 10_000;

// Must match the notification URL generated by sw.js, which cannot import this module.
const DEEP_LINK_PARAM = "session";

function deepLinkSessionId() {
  try {
    return new URLSearchParams(window.location.search).get(DEEP_LINK_PARAM);
  } catch (_) {
    return null;
  }
}

function clearDeepLink() {
  try {
    const url = new URL(window.location.href);
    if (!url.searchParams.has(DEEP_LINK_PARAM)) return;
    url.searchParams.delete(DEEP_LINK_PARAM);
    window.history.replaceState(null, "", url.pathname + url.search + url.hash);
  } catch (_) { /* Leaving the parameter is harmless when the History API is unavailable. */ }
}

function deadHint(state) {
  return state === "resumable"
    ? "This session can be resumed."
    : "This session is " + stateBadge(state).label + ". Resume it to continue.";
}

// Per-session retry state prevents one session's mark from superseding another's.
const readPosters = new Map();

const READ_RETRY_DELAY_MS = 2000;

// Snapshot pruning bounds retry timers for long-lived pages.
function pruneReadPosters(ids) {
  for (const [id, poster] of readPosters) {
    if (ids.has(id)) continue;
    if (poster.timer !== null) clearTimeout(poster.timer);
    readPosters.delete(id);
  }
}

// Coalesce to the newest seq and retry transport failures; the daemon remains the unread authority.
// Definite HTTP failures are terminal because retrying cannot change their outcome.
function postRead(id, seq) {
  let poster = readPosters.get(id);
  if (!poster) {
    poster = { seq: 0, inFlight: false, timer: null };
    readPosters.set(id, poster);
  }
  poster.seq = Math.max(poster.seq, seq);
  deliverRead(id, poster);
}

function deliverRead(id, poster) {
  if (poster.inFlight || poster.timer !== null) return;
  poster.inFlight = true;
  const attempted = poster.seq;
  apiRequest("/sessions/" + encodeURIComponent(id) + "/read", {
    method: "POST",
    body: JSON.stringify({ seq: attempted }),
  }).then(() => {
    poster.inFlight = false;
    if (readPosters.get(id) !== poster) return;
    if (poster.seq > attempted) deliverRead(id, poster);
  }).catch((e) => {
    poster.inFlight = false;
    if (readPosters.get(id) !== poster) return;
    if (isDefiniteAnswer(e)) return;
    poster.timer = setTimeout(() => {
      poster.timer = null;
      if (readPosters.get(id) === poster) deliverRead(id, poster);
    }, READ_RETRY_DELAY_MS);
  });
}

// activeId survives board navigation; only the visible session screen may trigger mark-read.
let sessionViewOnScreen = true;

// Imperative triggers can retry a failed POST even when unread and seq do not change.
// Archived rows remain selectable and therefore follow the same read contract.
function markReadIfViewing(id, unread, lastSeq) {
  if (!id || !(unread > 0)) return;
  // Visibility is intentionally looser than focus, which browser chrome and devtools can own.
  if (document.visibilityState !== "visible") return;
  if (!sessionViewOnScreen) return;
  postRead(id, lastSeq);
}

function detachedHint(session) {
  return session
    ? "Detached from " + displayName(session) + ". The agent keeps running."
    : "Terminal detached.";
}

// Project rows lack revisions and event frames, so ordered reads replace the entire list.
const reloadProjectsQueue = createSerialRefresh({
  read: async () => {
    const response = await fetchProjects();
    if (Array.isArray(response)) return response;
    return response && Array.isArray(response.projects) ? response.projects : [];
  },
  begin: () => projectsReadiness.begin(),
  succeed: (rows) => replaceProjects(rows),
  // Failed revalidation preserves rows that have already loaded.
  fail: (token, error) => projectsReadiness.fail(token, projectFailureSentence(error)),
  report: (error) => say(projectsReadiness.status.value.state === READY
    ? "Could not refresh projects: " + errorMessage(error)
    : projectFailureSentence(error), true),
});

function projectFailureSentence(error) {
  return "Could not load projects: " + errorMessage(error);
}

function App() {
  // Render-body signal reads subscribe this component to the shared stores.
  const sessions = sessionsSignal.value;
  const sessionsReady = sessionsReadiness.status.value.state === READY;
  const tasks = tasksSignal.value;
  const projects = projectsSignal.value;
  // Preserve idle, loading, ready, and failed so the picker can distinguish each outcome.
  const taskListStatus = tasksReadiness.status.value;
  const projectListStatus = projectsReadiness.status.value;
  const pendingAction = pendingMutation.value;
  const activeId = activeSessionId.value;
  const activeSession = activeSessionSignal.value;
  const dialog = dialogSignal.value;
  const status = statusSignal.value;
  const prefs = prefsSignal.value;
  const [projectId, setProjectId] = useState(null);
  const [route, setRoute] = useState(() => parseRoute(window.location.pathname, window.location.search));
  const [currentVersion, setCurrentVersion] = useState("");
  const [attachedId, setAttachedId] = useState(null);
  const [palette, setPalette] = useState(null);
  const [showDone, setShowDone] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(loadSidebarCollapsed);
  const [hint, setHint] = useState(SELECT_HINT);
  const [drawerOpen, setDrawerOpen] = useState(false);

  const onBoard = route.screen === SCREEN_TASKS || route.screen === SCREEN_TASK;
  sessionViewOnScreen = !onBoard;

  const openPalette = useCallback((mode = "leader") => setPalette({ mode: mode }), []);
  const closePalette = useCallback(() => setPalette(null), []);
  useEffect(() => { persistSidebarCollapsed(sidebarCollapsed); }, [sidebarCollapsed]);
  useEffect(() => subscribeToRoute(setRoute), []);

  const openTaskEntry = route.screen === SCREEN_TASK ? findTask(route.id) : null;

  // Hold a notification target until a matching row exists.
  const deepLinkRef = useRef(deepLinkSessionId());
  // Announce each outage once so the reconnect loop does not flood the aria-live region.
  const disconnectAnnouncedRef = useRef(false);
  // lib/reattach.js owns decisions; these refs hold machine state and the one timer and one probe it
  // can have in flight, each stamped with the generation that armed it.
  const reattachRef = useRef(null);
  if (reattachRef.current === null) reattachRef.current = initialReattachState();
  const reattachTimerRef = useRef(null);
  const reattachProbeRef = useRef(null);
  const projectRefreshStartedRef = useRef(false);

  // Capture before xterm/forms; KeyboardEvent.code keeps the shortcut physical across layouts.
  useEffect(() => {
    const handler = (event) => {
      const opensPalette =
        (event.metaKey && event.code === "KeyK") ||
        (event.ctrlKey && event.shiftKey && event.code === "KeyK");
      // Safari also maps Command-period to stop-loading, so suppress it in capture phase.
      const togglesSidebar = event.metaKey && event.code === "Period";
      if ((!opensPalette && !togglesSidebar) || dialogSignal.value) return;
      event.preventDefault();
      event.stopPropagation();
      if (togglesSidebar) {
        setSidebarCollapsed((collapsed) => !collapsed);
        return;
      }
      setPalette((current) => current
        ? { mode: current.mode === "search" ? "leader" : "search" }
        : { mode: "leader" });
    };
    document.addEventListener("keydown", handler, true);
    return () => document.removeEventListener("keydown", handler, true);
  }, []);

  // Stable dispatcher: read the world, reduce, store, then perform effects.
  const dispatchReattach = useCallback(function dispatch(event) {
    const step = reduceReattach(reattachRef.current, event, {
      visible: document.visibilityState === "visible",
      activeSessionId: activeSessionId.value,
      pending: pendingMutation.value,
    });
    reattachRef.current = step.state;
    for (const effect of step.effects) {
      switch (effect.kind) {
        case SCHEDULE: {
          // The zero-delay boundary prevents Preact batching detach→same-id attach into no state change.
          const handle = setTimeout(() => {
            const timer = reattachTimerRef.current;
            if (timer && timer.gen === effect.gen) reattachTimerRef.current = null;
            dispatch(timerFired(effect.gen));
          }, 0);
          reattachTimerRef.current = { gen: effect.gen, handle: handle };
          break;
        }
        case CANCEL_TIMER: {
          const timer = reattachTimerRef.current;
          if (!timer || timer.gen !== effect.gen) break;
          reattachTimerRef.current = null;
          clearTimeout(timer.handle);
          break;
        }
        case PROBE: {
          // The events socket may also be stale, so liveness is read over HTTP rather than assumed.
          const controller = new AbortController();
          const livenessTimeout = setTimeout(() => controller.abort(), REATTACH_LIVENESS_TIMEOUT_MS);
          reattachProbeRef.current = { gen: effect.gen, controller: controller };
          // Release both handles on every outcome.
          const settle = () => {
            clearTimeout(livenessTimeout);
            const probe = reattachProbeRef.current;
            if (probe && probe.gen === effect.gen) reattachProbeRef.current = null;
          };
          // Two handlers, not a `.catch` link: a throw while performing the resolved effects would
          // otherwise be reported as a dead session, for a generation the reducer has already retired.
          void apiRequest("/sessions/" + encodeURIComponent(effect.id), { signal: controller.signal })
            .then(
              (row) => {
                settle();
                dispatch(probeResolved(effect.gen, row));
              },
              (err) => {
                settle();
                dispatch(probeFailed(effect.gen, { definite: isDefiniteAnswer(err) }));
              },
            );
          break;
        }
        case ABORT_PROBE: {
          const probe = reattachProbeRef.current;
          if (!probe || probe.gen !== effect.gen) break;
          reattachProbeRef.current = null;
          probe.controller.abort();
          break;
        }
        case ATTACH:
          setAttachedId(effect.id);
          break;
        case HINT_DEAD:
          setHint(deadHint(effect.state));
          break;
        // Only a failed liveness read reaches this generic detached hint.
        case HINT_DETACHED:
          setHint(detachedHint(null));
          break;
        case HINT_CLEAR:
          setHint(null);
          break;
        default:
          break;
      }
    }
  }, []);

  const reloadProjects = useCallback((reportFailure = true) => reloadProjectsQueue(reportFailure), []);

  // Project changes have no event frame. Refresh on mount, board entry and foregrounding.
  useEffect(() => {
    projectsReadiness.setLoader(reloadProjects);
    const first = !projectRefreshStartedRef.current;
    projectRefreshStartedRef.current = true;
    if (first || onBoard) reloadProjects();
    if (!onBoard) return undefined;

    let pageWasAway = false;
    const markPageAway = () => {
      pageWasAway = true;
    };
    const refreshAfterReturn = () => {
      if (!pageWasAway || document.visibilityState !== "visible") return;
      pageWasAway = false;
      reloadProjects(false);
    };
    const trackVisibility = () => {
      if (document.visibilityState === "hidden") {
        markPageAway();
      } else {
        refreshAfterReturn();
      }
    };
    window.addEventListener("blur", markPageAway);
    window.addEventListener("focus", refreshAfterReturn);
    document.addEventListener("visibilitychange", trackVisibility);
    return () => {
      window.removeEventListener("blur", markPageAway);
      window.removeEventListener("focus", refreshAfterReturn);
      document.removeEventListener("visibilitychange", trackVisibility);
    };
  }, [onBoard, reloadProjects]);

  // Refresh while the picker is open because project changes have no event frame.
  const linkPickerOpen = dialog !== null && dialog.kind === "link-task";
  useEffect(() => {
    if (linkPickerOpen) reloadProjects(false);
  }, [linkPickerOpen, reloadProjects]);

  useEffect(() => {
    if (projects.length === 0) return;
    setProjectId((current) =>
      current && projects.some((project) => project.id === current) ? current : projects[0].id);
  }, [projects]);

  const selectProject = useCallback((id) => {
    setProjectId(id);
    setDrawerOpen(false);
  }, []);

  const projectCreated = useCallback(async (created) => {
    const rows = await reloadProjects();
    const label = (created && created.name) || "the project";
    if (created && created.archived === true) {
      throw new Error("Project " + label + " was deleted again while it was being adopted. " +
        "Restore it before trying again.");
    }
    if (!rows) {
      throw new Error("Project " + label + " may be ready, but the live project list could not be re-read. " +
        "Reload the page before using it.");
    }
    if (!created || !created.id || !rows.some((project) => project.id === created.id)) {
      throw new Error("Project " + label + " is no longer live. Restore it before trying again.");
    }
    setProjectId(created.id);
  }, [reloadProjects]);

  // Project mutations have no event frame, so refresh the live list explicitly. The refresh is this
  // mutation's own follow-up read and runs inside the lock, like the link's badge re-read.
  const applyProjectArchive = useCallback((id, archived) => {
    const submittedDialog = dialogSignal.value;
    const reportFailure = (e) => {
      // A dismissed dialog cannot own errors from its still-running request.
      if (dialogSignal.value === submittedDialog) throw e;
      say((archived ? "Could not delete the project: " : "Could not restore the project: ") +
        errorMessage(e), true);
    };
    return runMutation(archived ? "delete-project" : "restore-project", async () => {
      let changed;
      try {
        changed = archived ? await deleteProject(id) : await restoreProject(id);
      } catch (e) {
        reportFailure(e);
        return;
      }
      const label = (changed && changed.name) || id;
      if (!changed || typeof changed.archived !== "boolean") {
        reportFailure(new Error(
          "The daemon did not confirm whether " + label + " is deleted. Reload and try again.",
        ));
        return;
      }
      if (changed.archived !== archived) {
        reportFailure(new Error(archived
          ? label + " was restored again while it was being deleted. Delete it again if needed."
          : label + " was deleted again while it was being restored. Restore it again."));
        return;
      }
      // The response confirmed this row, so apply it before the refetch: a re-read that fails must not
      // leave a deleted project selected and interactive against its own tombstone.
      if (archived) removeProjectRow(id);
      else applyProjectRow(changed);
      if (archived) setProjectId((current) => current === id ? null : current);
      else setProjectId(id);

      const rows = await reloadProjects();
      // Restore selects its row; delete only repairs a selection that is no longer live.
      if (rows && rows.length === 0) setProjectId(null);
      if (rows && !archived && rows.some((project) => project.id === id)) setProjectId(id);
      closeDialogFrom(submittedDialog);
      const done = archived
        ? "Deleted " + label + ". Restore brings it back with its backlog."
        : "Restored " + label + ".";
      // Preserve the reload failure instead of reporting unqualified success.
      say(rows ? done : done + " The project list could not be re-read — reload the page.", !rows);
    });
  }, [reloadProjects]);

  const removeProject = useCallback((id) => applyProjectArchive(id, true), [applyProjectArchive]);
  const bringBackProject = useCallback((id) => applyProjectArchive(id, false), [applyProjectArchive]);

  // Treat stale IDs absent from the live project list as no selection.
  const selectedProject = findProject(projectId);
  const selectedProjectId = selectedProject ? selectedProject.id : null;

  const showSession = useCallback((session) => {
    selectSessionId(session.id);
    dispatchReattach(cancelReattachEvent());
    setDrawerOpen(false);
    // The route is the owner of both the visible screen and selected session.
    navigate(sessionPath(session.id));
    if (isAliveState(session.state)) {
      dispatchReattach(grantReattach());
      setAttachedId(session.id);
      setHint(null);
    } else {
      setAttachedId(null);
      setHint(deadHint(session.state));
    }
    // The caller may hold a row the shared list has not merged yet; judge unread from what it handed us.
    markReadIfViewing(session.id, session.unread, session.lastSeq);
  }, [dispatchReattach]);

  const selectSession = useCallback((id) => {
    const session = findSession(id);
    if (session) showSession(session);
  }, [showSession]);

  // Route targets wait for their row. A bare "/" intentionally preserves the current terminal.
  const routeSessionId = route.screen === SCREEN_SESSIONS ? route.id : null;
  useEffect(() => {
    if (!routeSessionId || routeSessionId === activeId) return;
    const target = sessions.find((s) => s.id === routeSessionId);
    if (!target) return;
    // Retire the retained target so a later duplicate row cannot re-select it.
    if (deepLinkRef.current === routeSessionId) deepLinkRef.current = null;
    showSession(target);
  }, [routeSessionId, sessions, activeId, showSession]);

  // Apply a task route's project once per ref so later manual project selection remains authoritative.
  const appliedTaskProjectRef = useRef(null);
  const openTaskRef = route.screen === SCREEN_TASK ? route.id : null;
  useEffect(() => {
    if (!openTaskRef) { appliedTaskProjectRef.current = null; return; }
    if (appliedTaskProjectRef.current === openTaskRef) return;
    const entry = tasks.find((task) => task.ref === openTaskRef);
    if (!entry) return;
    // Archived cards remain deep-linkable but cannot select a missing sidebar row. Leave this retryable
    // so a later project refresh can adopt a restored row or resolve an initial fetch race.
    if (!projects.some((project) => project.id === entry.project)) return;
    appliedTaskProjectRef.current = openTaskRef;
    setProjectId(entry.project);
  }, [openTaskRef, tasks, projects]);

  // Returning from the board must retry mark-read even if the session emitted no new frame.
  useEffect(() => {
    if (onBoard) return;
    const s = activeSessionSignal.value;
    if (s) markReadIfViewing(s.id, s.unread, s.lastSeq);
  }, [onBoard]);

  const applySessionsSnapshot = useCallback((rows) => {
    // Reconnect snapshots are authoritative, including deletions, and are also the only attention
    // transition carrier for changes made while the socket was down.
    const { previous, first } = replaceSessions(rows);
    for (const row of rows) {
      const prevRow = previous.find((s) => s.id === row.id);
      if (prevRow && !prevRow.needsAttention && row.needsAttention) notifyAttention(prevRow);
    }
    const ids = new Set(rows.map((s) => s.id));
    pruneSelection(ids);
    setAttachedId((id) => (id && !ids.has(id) ? null : id));
    pruneReadPosters(ids);
    dispatchReattach(snapshotApplied(ids));
    for (const row of rows) dispatchReattach(sessionStateChanged(row.id, row.state));
    const wanted = deepLinkRef.current;
    if (wanted) {
      const target = rows.find((s) => s.id === wanted);
      if (target) {
        deepLinkRef.current = null;
        clearDeepLink();
        showSession(target);
      }
    }
    // Judge unread from the authoritative frame.
    const active = rows.find((s) => s.id === activeSessionId.value);
    if (active) markReadIfViewing(active.id, active.unread, active.lastSeq);
    disconnectAnnouncedRef.current = false;
    // Do not repeat the routine count into the aria-live region after reconnects.
    if (first) say(rows.length + " session(s).");
  }, [dispatchReattach, showSession]);

  const applySessionRow = useCallback((row) => {
    const { changed, previous, winner } = mergeSessionRow(row);
    if (winner) dispatchReattach(sessionStateChanged(winner.id, winner.state));
    if (changed && previous && !previous.needsAttention && row.needsAttention) {
      notifyAttention(previous);
    }
    if (deepLinkRef.current === row.id) {
      deepLinkRef.current = null;
      clearDeepLink();
      if (winner) showSession(winner);
      return winner;
    }
    if (winner && winner.id === activeSessionId.value) {
      markReadIfViewing(winner.id, winner.unread, winner.lastSeq);
    }
    return winner;
  }, [showSession]);

  const applySessionPatch = useCallback((msg) => {
    const { changed, previous, winner } = mergeSessionPatch(msg);
    // A patch for a row this page has never seen carries too little to publish, so there is nothing to
    // poke a read against either.
    if (!winner) return;
    dispatchReattach(sessionStateChanged(winner.id, winner.state));
    if (changed && !previous.needsAttention && msg.needsAttention) notifyAttention(previous);
    // Even a stale patch retries a stalled mark-read POST without rewriting the signal.
    if (winner.id === activeSessionId.value) {
      markReadIfViewing(winner.id, winner.unread, winner.lastSeq);
    }
  }, []);

  // Targeted GETs return the revision winner; null is reserved for an unavailable read.
  const fetchSessionRow = useCallback(async (id) => {
    try {
      const row = await apiRequest("/sessions/" + encodeURIComponent(id));
      if (row && row.id) {
        return applySessionRow(row);
      }
    } catch (_) {}
    return null;
  }, [applySessionRow]);
  const fetchSessionRowRef = useRef(fetchSessionRow);
  fetchSessionRowRef.current = fetchSessionRow;

  // Revision ordering prevents this initial GET from rolling back a concurrent save or WS update.
  useEffect(() => {
    let stopped = false;
    apiRequest("/preferences")
      .then((value) => { if (!stopped) applyServerPreferences(value); })
      .catch((e) => {
        if (stopped) return;
        // apiRequest is already leaving for the sign-in page; a sentence nobody reads adds nothing.
        if (isUnauthenticated(e)) return;
        say("Could not load preferences: " + errorMessage(e), true);
      });
    return () => { stopped = true; };
  }, []);

  useEffect(() => {
    let stopped = false;
    apiRequest("/version")
      .then((info) => {
        if (!stopped && info && typeof info.version === "string") {
          setCurrentVersion(info.version);
        }
      })
      .catch(() => {});
    return () => { stopped = true; };
  }, []);

  // Dispatch through a ref to keep one socket while reconnect snapshots restore the baseline.
  const onSessionsFrame = useCallback((msg) => {
    if (msg.type === "sessions_snapshot") applySessionsSnapshot(msg.sessions);
    else if (msg.type === "session_row") applySessionRow(msg.session);
    else if (msg.type === "session_update") applySessionPatch(msg);
    else if (msg.type === "tasks_snapshot") replaceTasks(msg.tasks);
    else if (msg.type === "task_row") mergeTaskRow(msg.task);
    else if (msg.type === "task_update") mergeTaskPatch(msg.task);
    else if (msg.type === "task_removed") dropTask(msg.ref);
    else if (msg.type === "usage_snapshot") replaceUsage(msg.windows, msg.serverNow);
    else if (msg.type === "usage_update") mergeUsageWindow(msg.window, msg.serverNow);
  }, [applySessionsSnapshot, applySessionRow, applySessionPatch]);
  const sessionsFrameRef = useRef(onSessionsFrame);
  sessionsFrameRef.current = onSessionsFrame;
  // The deps stay empty: `opened` below is what tells a first open from a recovery, and a torn-down
  // effect resets it, so a terminal dropped while the daemon was unreachable would never be reattached.
  useEffect(() => {
    let socket = null;
    let timer = null;
    let stopped = false;
    let opened = false;

    const connect = () => {
      if (stopped) return;
      try {
        socket = new WebSocket(wsUrl("/events"));
      } catch (e) {
        // The list has no HTTP fallback, so keep reconnecting.
        say("events WS error: " + e, true);
        timer = setTimeout(connect, 2000);
        return;
      }
      socket.onopen = () => {
        // Event-socket recovery grants a fresh owned terminal liveness check.
        if (opened) dispatchReattach(grantAndSchedule());
        opened = true;
      };
      socket.onmessage = (ev) => {
        let msg;
        try { msg = JSON.parse(ev.data); } catch (_) { return; }
        if (!msg) return;
        if (msg.type === "preferences_update") {
          applyServerPreferences(msg);
          return;
        }
        sessionsFrameRef.current(msg);
      };
      socket.onclose = () => {
        if (stopped) return;
        if (!disconnectAnnouncedRef.current) {
          disconnectAnnouncedRef.current = true;
          say("Daemon connection lost — reconnecting…", true);
        }
        timer = setTimeout(connect, 2000);
      };
      socket.onerror = () => {};
    };

    connect();
    return () => {
      stopped = true;
      clearTimeout(timer);
      if (socket) {
        socket.onclose = null;
        try { socket.close(); } catch (_) {}
      }
    };
  }, []);

  // Foregrounding retries mark-read after hidden-tab updates were deliberately suppressed.
  useEffect(() => {
    const onVisibilityChange = () => {
      const s = activeSessionSignal.value;
      if (s) markReadIfViewing(s.id, s.unread, s.lastSeq);
    };
    document.addEventListener("visibilitychange", onVisibilityChange);
    return () => document.removeEventListener("visibilitychange", onVisibilityChange);
  }, []);

  // The service worker sends a session id when a notification focuses an existing page.
  useLayoutEffect(() => {
    if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return undefined;
    const onMessage = (event) => {
      const msg = event.data;
      if (!msg || msg.type !== "select-session" || !msg.sessionId) return;
      if (findSession(msg.sessionId)) {
        // A newer tap supersedes any retained target whose row may arrive later.
        deepLinkRef.current = null;
        clearDeepLink();
        selectSession(msg.sessionId);
        return;
      }
      // A backgrounded page may be stale; retain the target while fetching its row.
      deepLinkRef.current = msg.sessionId;
      fetchSessionRowRef.current(msg.sessionId);
    };
    navigator.serviceWorker.addEventListener("message", onMessage);
    return () => navigator.serviceWorker.removeEventListener("message", onMessage);
  }, [selectSession]);

  // Mobile suspension may drop the terminal socket. Foregrounding grants one ordered reattach attempt.
  useEffect(() => {
    const reconnectWhenVisible = () => {
      dispatchReattach(document.visibilityState === "visible" ? grantAndSchedule() : pageHidden());
    };

    document.addEventListener("visibilitychange", reconnectWhenVisible);
    return () => {
      document.removeEventListener("visibilitychange", reconnectWhenVisible);
      dispatchReattach(cancelReattachEvent());
    };
  }, [dispatchReattach]);

  const startSession = useCallback((body) => {
    const submittedDialog = dialogSignal.value;
    // Auto-select only if no selection event occurred during the request. Selection generation is not
    // run currency: the operator can navigate away and back while this one mutation stays current.
    const selectionUnmoved = markSelection();
    return runMutation("start", async () => {
      let created;
      try {
        created = await apiRequest("/sessions", {
          method: "POST",
          body: JSON.stringify(body),
        });
      } catch (e) {
        // Late failures surface globally if the submitting form has unmounted.
        if (dialogSignal.value === submittedDialog) throw e;
        say("Could not start session: " + errorMessage(e), true);
        return;
      }
      mergeSessionRow(created);
      closeDialogFrom(submittedDialog);
      say("Started " + displayName(created) + ".");
      if (selectionUnmoved()) showSession(created);
    });
  }, [showSession]);

  const renameSession = useCallback((sessionId, name) => {
    const submittedDialog = dialogSignal.value;
    return runMutation("rename", async () => {
      let renamed;
      try {
        renamed = await apiRequest("/sessions/" + encodeURIComponent(sessionId), {
          method: "PATCH",
          body: JSON.stringify({ name: name }),
        });
      } catch (e) {
        // Late failures surface globally if the submitting form has unmounted.
        if (dialogSignal.value === submittedDialog) throw e;
        say("Could not rename the session: " + errorMessage(e), true);
        return;
      }
      mergeSessionRow(renamed);
      closeDialogFrom(submittedDialog);
      say("Renamed to " + displayName(renamed) + ".");
    });
  }, []);

  // Import and optional resume are serialized as one action. HTTP rows merge by revision, targeted
  // GETs decide attachment from fresh state, and generation guards prevent late auto-selection.
  // Registration success closes the dialog even when its follow-up resume fails.
  const importSession = useCallback((body, registerOnly) => {
    const submittedDialog = dialogSignal.value;
    const selectionUnmoved = markSelection();
    return runMutation("import", async () => {
      let created;
      try {
        created = await apiRequest("/sessions/import", {
          method: "POST",
          body: JSON.stringify(body),
        });
      } catch (e) {
        if (dialogSignal.value === submittedDialog) throw e;
        say(errorMessage(e), true);
        return;
      }
      // Fetch after commit; fall back to the committed 201 row if the read is unavailable. Both this
      // read and the post-resume one belong to the import, so they run inside its lock.
      const fetched = await fetchSessionRow(created.id);
      const registered = fetched || created;
      if (!fetched) mergeSessionRow(created);
      closeDialogFrom(submittedDialog);
      if (registerOnly) {
        if (fetched) say("Imported " + displayName(registered) + " — registered only.");
        if (selectionUnmoved()) showSession(registered);
        return;
      }
      try {
        const resumedDto = await apiRequest(
          "/sessions/" + encodeURIComponent(created.id) + "/resume",
          { method: "POST" },
        );
        // Re-read after resume so an immediate exit cannot attach using stale live state.
        const freshRow = await fetchSessionRow(created.id);
        // The resume DTO is the best fallback; the pre-resume row would suppress attachment.
        const row = freshRow || (resumedDto && resumedDto.id ? resumedDto : registered);
        if (!freshRow && resumedDto && resumedDto.id) mergeSessionRow(resumedDto);
        if (freshRow) say("Imported and resumed " + displayName(row) + ".");
        if (selectionUnmoved()) showSession(row);
      } catch (e) {
        const after = await fetchSessionRow(created.id);
        if (selectionUnmoved()) showSession(after || registered);
        say("Imported, but resume failed: " + errorMessage(e), true);
      }
    });
  }, [fetchSessionRow, showSession]);

  const controlSession = useCallback(async (action, id) => {
    const s = findSession(id || activeSessionId.value);
    if (!s) return;
    // Refuse before the confirmation, not after: a stop that cannot be sent must not first ask the
    // operator whether to send it.
    if (pendingMutation.value) {
      say(MUTATION_BUSY_MESSAGE, true);
      return;
    }
    if (action === "stop" &&
        !window.confirm("Stop " + displayName(s) + "? The conversation can be resumed later.")) {
      return;
    }
    if (action === "done" &&
        !window.confirm("Mark " + displayName(s) + " done? This stops the agent and hides the session.")) {
      return;
    }
    if (action === "stop" || action === "done" || action === "resume") {
      dispatchReattach(cancelReattachEvent());
    }

    try {
      // The action is the lock's name: lib/commands.js reads it back to decide which controls a
      // stop/done/resume/import in flight may not share the attachment with.
      await runMutation(action, async () => {
        const progress = say(capitalize(action) + " in progress…");
        const updated = await apiRequest(
          "/sessions/" + encodeURIComponent(s.id) + "/" + encodeURIComponent(action),
          { method: "POST" },
        );
        if (updated && updated.id) {
          mergeSessionRow(updated);
          dispatchReattach(sessionStateChanged(updated.id, updated.state));
        }
        if (action === "stop" || action === "done") {
          if (s.id === activeSessionId.value) setAttachedId(null);
          setHint(action === "done"
            ? "Marked done. The archive toggle in the sidebar header brings it back."
            : "Session stopped. Resume it to continue.");
        } else if (action === "resume") {
          dispatchReattach(grantReattach());
          // Do not attach over a newer selection or erase the hint that selection installed.
          if (s.id === activeSessionId.value) {
            setAttachedId(s.id);
            setHint(null);
          }
        }
        // Replace only this flow's progress message; preserve newer announcements.
        if (announcementHolds(progress)) {
          say(capitalize(action) + " completed for " + displayName(s) + ".");
        }
      });
    } catch (e) {
      say(capitalize(action) + " failed: " + errorMessage(e), true);
    }
  }, [dispatchReattach]);

  // Local attach/detach must not race actions that can rewrite attachment state.
  const attach = useCallback(() => {
    if (!activeSessionId.value) return;
    if (affectsAttachment(pendingMutation.value)) {
      say(MUTATION_BUSY_MESSAGE, true);
      return;
    }
    dispatchReattach(cancelReattachEvent());
    dispatchReattach(grantReattach());
    setAttachedId(activeSessionId.value);
    setHint(null);
  }, [dispatchReattach]);

  const detach = useCallback(() => {
    if (affectsAttachment(pendingMutation.value)) {
      say(MUTATION_BUSY_MESSAGE, true);
      return;
    }
    const s = activeSessionSignal.value;
    dispatchReattach(cancelReattachEvent());
    setAttachedId(null);
    setHint(detachedHint(s));
  }, [dispatchReattach]);

  // Report async copy results outside the palette because its aria-live region unmounts immediately.
  const copyTmuxCommand = useCallback(async () => {
    const s = activeSessionSignal.value;
    const command = s && isAliveState(s.state) && s.tmuxSession
      ? tmuxAttachCommand(s.tmuxSession)
      : "";
    if (!command) {
      say("Could not copy tmux command: select a live session with a tmux name.", true);
      return;
    }
    try {
      await writeClipboard(command);
      say("Tmux command copied to clipboard.");
    } catch (_) {
      say("Could not copy the tmux command.", true);
    }
  }, []);

  const onTerminalClosed = useCallback((id) => {
    const s = findSession(id);
    dispatchReattach(terminalClosed(id, s ? s.state : null));
    setAttachedId((current) => (current === id ? null : current));
    if (activeSessionId.value === id) setHint(detachedHint(s));
  }, [dispatchReattach]);

  // Dialogs can close or remount while saving, so component-local busy state cannot serialize PUTs.
  // The shared mutation lock outlives any one dialog instance, so it can.
  const savePreferences = useCallback((next) => {
    const submittedDialog = dialogSignal.value;
    // Form revision distinguishes a remounted PreferencesDialog when routing late failures.
    const revisionAtSubmit = prefsSignal.value.revision;
    return runMutation("preferences", async () => {
      try {
        const saved = await apiRequest("/preferences", {
          method: "PUT",
          body: JSON.stringify({
            basePath: next.basePath,
            groupingLevel: next.groupingLevel,
          }),
        });
        // A WS echo may beat this response: equal revision is this save, while strictly newer external
        // state wins and keeps the refreshed form open. An unreadable 2xx body is the third answer and
        // applies nothing — it cannot establish what the daemon committed, so the save is a failure.
        const outcome = applyServerPreferences(saved);
        if (outcome === PREFS_UNREADABLE) {
          throw new Error("the daemon answered the save with an unreadable preferences payload");
        }
        applyDevicePreferences(next);
        if (outcome === PREFS_SUPERSEDED) {
          say("Preferences were saved, but newer settings arrived. Review the current values.");
          return;
        }
        closeDialogFrom(submittedDialog);
        const current = serverPrefs.value;
        say(current.basePath.length > 0
          ? "Grouping by " + current.basePath + " (level " + current.groupingLevel + ")."
          : "Grouping off — no base path set.");
      } catch (e) {
        // Late failures surface globally if the submitting form has unmounted.
        if (dialogSignal.value === submittedDialog && prefsSignal.value.revision === revisionAtSubmit) throw e;
        say("Could not save preferences: " + errorMessage(e), true);
      }
    });
  }, []);

  const openNewSession = useCallback((cwd, initialMode = "start", initialAgent = "", taskRef = null) => {
    const selected = activeSessionSignal.value;
    openDialog({
      kind: "new",
      cwd: cwd || (selected && selected.cwd) || prefsSignal.value.basePath,
      initialMode: initialMode,
      initialAgent: initialAgent,
      taskRef: taskRef,
    });
  }, []);
  const openImportSession = useCallback(() => openNewSession(null, "import"), [openNewSession]);
  const openFreeTerminal = useCallback(
    () => openNewSession(null, "start", "shell"),
    [openNewSession],
  );
  const startSessionForTask = useCallback(
    (cwd, taskRef) => openNewSession(cwd, "start", "", taskRef),
    [openNewSession],
  );

  const openBoard = useCallback(() => navigate(routePath({ screen: SCREEN_TASKS, id: null })), []);
  // Preserve selection and attachment when leaving the board; avoid showSession's side effects.
  const openSessions = useCallback(() => {
    const id = activeSessionId.value;
    navigate(routePath({ screen: SCREEN_SESSIONS, id: id }));
  }, []);
  // Counters let repeated commands retrigger while the board remains mounted.
  const [newTaskRequest, setNewTaskRequest] = useState(0);
  const newTask = useCallback(() => {
    navigate(routePath({ screen: SCREEN_TASKS, id: null }));
    setNewTaskRequest((n) => n + 1);
  }, []);
  const [newProjectRequest, setNewProjectRequest] = useState(0);
  const newProject = useCallback(() => {
    navigate(routePath({ screen: SCREEN_TASKS, id: null }));
    setNewProjectRequest((n) => n + 1);
  }, []);
  // Reset before remount so stale requests cannot reopen forms on a later board visit.
  useEffect(() => {
    if (!onBoard) {
      setNewTaskRequest(0);
      setNewProjectRequest(0);
    }
  }, [onBoard]);
  const openSessionTask = useCallback(() => {
    const selected = activeSessionSignal.value;
    if (selected && selected.taskRef) navigate(taskPath(selected.taskRef));
  }, []);

  const linkSessionToTask = useCallback(async (sessionId, ref, expectedProjectId) => {
    const selected = findSession(sessionId);
    // The shared pre-POST re-check, not the picker's availability guard: the operator has already chosen
    // a task, and every input may have moved underneath the open dialog while they were choosing.
    if (sessionTaskLinkSubmitBlocked({
      session: selected,
      pendingAction: pendingMutation.value,
      activeSessionId: activeSessionId.value,
      sessionId: sessionId,
      expectedProjectId: expectedProjectId,
      projects: projectsSignal.value,
      task: findTask(ref),
    })) {
      throw new Error("The selected session or task changed. Close the picker and try again.");
    }

    const submittedDialog = dialogSignal.value;
    const label = displayName(selected);
    return runMutation("link-task", async () => {
      let failure = null;
      try {
        await linkTask(ref, sessionId);
      } catch (e) {
        failure = e;
      }
      if (failure) {
        // A dismissed picker has nowhere local to report the request failure.
        if (dialogSignal.value === submittedDialog) throw failure;
        say("Could not link " + label + " to " + ref + ": " + errorMessage(failure), true);
        return;
      }

      closeDialogFrom(submittedDialog);
      const refreshing = say("Link request completed for " + label + "; refreshing the session…");

      // Hold the mutation lock through the badge re-read so a second link cannot overtake it. The shared
      // request timeout bounds the wait; the revision merge arbitrates racing WebSocket frames.
      const fresh = await fetchSessionRow(sessionId);
      // Preserve newer feedback, such as an events-socket warning.
      if (!announcementHolds(refreshing)) return;
      const winner = findSession(sessionId) || fresh;
      const outcome = sessionTaskLinkOutcome({ label: label, ref: ref, fresh: fresh, winner: winner });
      say(outcome.text, outcome.error);
    });
  }, [fetchSessionRow]);

  const closeDrawer = useCallback(() => setDrawerOpen(false), []);
  const toggleDrawer = useCallback(() => setDrawerOpen((open) => !open), []);
  const toggleSidebar = useCallback(() => setSidebarCollapsed((collapsed) => !collapsed), []);

  const openPrefs = useCallback(() => openDialog({ kind: "prefs" }), []);
  const openHelp = useCallback(() => openDialog({ kind: "help" }), []);
  const openPhone = useCallback(() => openDialog({ kind: "phone" }), []);
  const openUpload = useCallback(() => {
    const selected = activeSessionSignal.value;
    if (selected) openDialog({ kind: "upload", session: selected });
  }, []);
  const openRename = useCallback(() => {
    const selected = activeSessionSignal.value;
    if (selected) openDialog({ kind: "rename", session: selected });
  }, []);
  const openLinkTask = useCallback(() => {
    const selected = activeSessionSignal.value;
    const disabled = sessionTaskLinkDisabledReason(selected, pendingMutation.value);
    if (disabled) {
      say("Linking a task is no longer available: " + disabled + ".", true);
      return;
    }
    openDialog({ kind: "link-task", session: selected });
  }, []);
  const openDeleteProject = useCallback(() => {
    if (selectedProject) openDialog({ kind: "delete-project", project: selectedProject });
  }, [selectedProject]);
  const openRestoreProject = useCallback(() => openDialog({ kind: "restore-project" }), []);

  const interrupt = useCallback(() => controlSession("interrupt"), [controlSession]);
  const resume = useCallback(() => controlSession("resume"), [controlSession]);
  const stop = useCallback(() => controlSession("stop"), [controlSession]);
  const done = useCallback(() => controlSession("done"), [controlSession]);
  const restore = useCallback((id) => controlSession("undone", id), [controlSession]);
  const toggleShowDone = useCallback(() => setShowDone((shown) => !shown), []);
  const changePaletteMode = useCallback((mode) => {
    setPalette((current) => current ? { mode: mode } : current);
  }, []);

  const commands = buildCommands({
    sessions: sessions,
    activeSession: activeSession,
    attachedId: attachedId,
    pendingAction: pendingAction,
    onBoard: onBoard,
    projectId: selectedProjectId,
    actions: {
      selectSession: selectSession,
      interrupt: interrupt,
      resume: resume,
      attach: attach,
      detach: detach,
      stop: stop,
      done: done,
      copyTmux: copyTmuxCommand,
      uploadFiles: openUpload,
      rename: openRename,
      linkSessionTask: openLinkTask,
      newSession: () => openNewSession(null),
      importSession: openImportSession,
      freeTerminal: openFreeTerminal,
      toggleShowDone: toggleShowDone,
      help: openHelp,
      phone: openPhone,
      preferences: openPrefs,
      openBoard: openBoard,
      openSessions: openSessions,
      newTask: newTask,
      newProject: newProject,
      deleteProject: openDeleteProject,
      restoreProject: openRestoreProject,
      openSessionTask: openSessionTask,
    },
  });

  return html`
    ${palette && html`
      <${CommandPalette}
        commands=${commands}
        mode=${palette.mode}
        onModeChange=${changePaletteMode}
        onClose=${closePalette}
      />`}
    ${""}
    ${drawerOpen && html`
      <button type="button" class="drawer-scrim" aria-label="Close the sidebar"
              onClick=${closeDrawer}></button>`}
    ${""}
    <${Sidebar}
      screen=${onBoard ? SCREEN_TASKS : SCREEN_SESSIONS}
      sessions=${sessions}
      tasks=${tasks}
      projects=${projects}
      projectId=${projectId}
      activeId=${activeId}
      prefs=${prefs}
      status=${status}
      currentVersion=${currentVersion}
      drawerOpen=${drawerOpen}
      collapsed=${sidebarCollapsed}
      showDone=${showDone}
      sessionsReady=${sessionsReady}
      onSelect=${selectSession}
      onSelectProject=${selectProject}
      onNewSession=${openNewSession}
      onNewProject=${newProject}
      onOpenPrefs=${openPrefs}
      onRestore=${restore}
      onCloseDrawer=${closeDrawer}
      onToggleShowDone=${toggleShowDone}
    />
    ${""}
    ${onBoard ? html`
      <${Board}
        tasks=${tasks}
        sessions=${sessions}
        route=${route}
        projects=${projects}
        projectId=${selectedProjectId}
        basePath=${prefs.basePath}
        newTaskRequest=${newTaskRequest}
        newProjectRequest=${newProjectRequest}
        drawerOpen=${drawerOpen}
        sidebarCollapsed=${sidebarCollapsed}
        onTaskRow=${mergeTaskRow}
        onProjectCreated=${projectCreated}
        onToggleDrawer=${toggleDrawer}
        onToggleSidebar=${toggleSidebar}
        onOpenPalette=${openPalette}
        onAnnounce=${say}
      />
      ${route.screen === SCREEN_TASK && html`
        <${TaskDetail} taskRef=${route.id} entry=${openTaskEntry} sessions=${sessions}
                       onTaskRow=${mergeTaskRow} onTaskRemoved=${dropTask}
                       onStartSession=${startSessionForTask} onAnnounce=${say} />`}
      <p id="board-status" class=${"status-line board-status" + (status.error ? " error" : "")}
         role="status" aria-live="polite">${status.text}</p>
    ` : html`
      <${TerminalPane}
        session=${activeSession}
        tasks=${tasks}
        attachedId=${attachedId}
        terminalFontSize=${prefs.terminalFontSize}
        terminalUnicode=${prefs.terminalUnicode}
        hint=${hint}
        drawerOpen=${drawerOpen}
        sidebarCollapsed=${sidebarCollapsed}
        onToggleDrawer=${toggleDrawer}
        onToggleSidebar=${toggleSidebar}
        onOpenPalette=${openPalette}
        onTerminalClosed=${onTerminalClosed}
      />
    `}
    ${dialog && dialog.kind === "new" && html`
      <${NewSessionDialog} initialCwd=${dialog.cwd} initialMode=${dialog.initialMode}
                           initialAgent=${dialog.initialAgent}
                           initialTaskRef=${dialog.taskRef}
                           basePath=${prefs.basePath}
                           onStart=${startSession} onImport=${importSession} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "upload" && html`
      <${UploadFilesDialog} session=${dialog.session} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "rename" && html`
      <${RenameSessionDialog} session=${dialog.session} onRename=${renameSession}
                              onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "link-task" && html`
      <${LinkTaskDialog} initialSession=${dialog.session} session=${activeSession}
                         tasks=${tasks} tasksStatus=${taskListStatus}
                         projectsStatus=${projectListStatus}
                         projectActive=${isLiveProject(dialog.session.projectId)}
                         onRetryProjects=${projectsReadiness.retry}
                         onLink=${linkSessionToTask} onClose=${closeDialog} />`}
    ${/* Remount on server revision so an open draft cannot overwrite newer committed values. */ ""}
    ${dialog && dialog.kind === "prefs" && html`
      <${PreferencesDialog} key=${prefs.revision} prefs=${prefs} sessions=${sessions}
                            onSave=${savePreferences} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "delete-project" && html`
      <${DeleteProjectDialog} project=${dialog.project}
                              taskCount=${taskListStatus.state === READY
                                ? tasks.filter((task) => task.project === dialog.project.id).length
                                : null}
                              onDelete=${removeProject} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "restore-project" && html`
      <${RestoreProjectDialog} onRestore=${bringBackProject} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "help" && html`<${HelpDialog} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "phone" && html`<${PhoneDialog} onClose=${closeDialog} />`}
  `;
}

// WebKit/iOS may report installed mode as fullscreen or only through navigator.standalone.
const appRoot = document.getElementById("app");
const installedApp =
  window.matchMedia("(display-mode: standalone)").matches ||
  window.matchMedia("(display-mode: fullscreen)").matches ||
  window.navigator.standalone === true;
appRoot.classList.toggle("installed-app", installedApp);
render(html`<${App} />`, appRoot);
