import { render } from "preact";
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from "preact/hooks";
import { html } from "htm/preact";

import {
  AUTH_PATH,
  apiRequest,
  errorMessage,
  isDefiniteAnswer,
  isUnauthenticated,
  wsUrl,
} from "./lib/api.js";
import { writeClipboard } from "./lib/clipboard.js";
import { affectsAttachment, buildCommands } from "./lib/commands.js";
import {
  loadPrefs,
  loadSidebarCollapsed,
  persistSidebarCollapsed,
  persistTerminalFontSize,
  persistTerminalUnicode,
  sanitizeServerPreferences,
} from "./lib/prefs.js";
import { notifyAttention } from "./lib/notify.js";
import {
  capitalize,
  displayName,
  isAliveState,
  patchIfNewer,
  stateBadge,
  tmuxAttachCommand,
  upsertIfNewer,
} from "./lib/sessions.js";
import {
  SCREEN_SESSIONS,
  SCREEN_TASK,
  SCREEN_TASKS,
  navigate,
  parseRoute,
  routePath,
  sessionPath,
  subscribeToRoute,
  taskPath,
} from "./lib/router.js";
import {
  applyTasksSnapshot,
  fetchProjects,
  patchTaskIfNewer,
  removeTask,
  upsertTaskIfNewer,
} from "./lib/tasks.js";
import { Board } from "./components/Board.js";
import { TaskDetail } from "./components/TaskDetail.js";
import { CommandPalette } from "./components/CommandPalette.js";
import { Sidebar } from "./components/Sidebar.js";
import { TerminalPane } from "./components/TerminalPane.js";
import {
  HelpDialog,
  NewSessionDialog,
  PhoneDialog,
  PreferencesDialog,
  UploadFilesDialog,
} from "./components/dialogs.js";

const SELECT_HINT = "Select a session on the left to attach its terminal.";
const REATTACH_LIVENESS_TIMEOUT_MS = 10_000;

// Must match the notification URL generated by sw.js, which cannot import this module.
const DEEP_LINK_PARAM = "session";

function deepLinkSessionId() {
  try {
    return new URLSearchParams(window.location.search).get(DEEP_LINK_PARAM);
  } catch (_) {
    return null;
  }
}

function clearDeepLink() {
  try {
    const url = new URL(window.location.href);
    if (!url.searchParams.has(DEEP_LINK_PARAM)) return;
    url.searchParams.delete(DEEP_LINK_PARAM);
    window.history.replaceState(null, "", url.pathname + url.search + url.hash);
  } catch (_) { /* Leaving the parameter is harmless when the History API is unavailable. */ }
}

function deadHint(state) {
  return state === "resumable"
    ? "This session can be resumed."
    : "This session is " + stateBadge(state).label + ". Resume it to continue.";
}

// Per-session retry state prevents one session's mark from superseding another's.
const readPosters = new Map();

const READ_RETRY_DELAY_MS = 2000;

// Snapshot pruning bounds retry timers for long-lived pages.
function pruneReadPosters(ids) {
  for (const [id, poster] of readPosters) {
    if (ids.has(id)) continue;
    if (poster.timer !== null) clearTimeout(poster.timer);
    readPosters.delete(id);
  }
}

// Coalesce to the newest seq and retry transport failures; the daemon remains the unread authority.
// Definite HTTP failures are terminal because retrying cannot change their outcome.
function postRead(id, seq) {
  let poster = readPosters.get(id);
  if (!poster) {
    poster = { seq: 0, inFlight: false, timer: null };
    readPosters.set(id, poster);
  }
  poster.seq = Math.max(poster.seq, seq);
  deliverRead(id, poster);
}

function deliverRead(id, poster) {
  if (poster.inFlight || poster.timer !== null) return;
  poster.inFlight = true;
  const attempted = poster.seq;
  apiRequest("/sessions/" + encodeURIComponent(id) + "/read", {
    method: "POST",
    body: JSON.stringify({ seq: attempted }),
  }).then(() => {
    poster.inFlight = false;
    if (readPosters.get(id) !== poster) return;
    if (poster.seq > attempted) deliverRead(id, poster);
  }).catch((e) => {
    poster.inFlight = false;
    if (readPosters.get(id) !== poster) return;
    if (isDefiniteAnswer(e)) return;
    poster.timer = setTimeout(() => {
      poster.timer = null;
      if (readPosters.get(id) === poster) deliverRead(id, poster);
    }, READ_RETRY_DELAY_MS);
  });
}

// activeId survives board navigation; only the visible session screen may trigger mark-read.
let sessionViewOnScreen = true;

// Imperative triggers can retry a failed POST even when unread and seq do not change.
// Archived rows remain selectable and therefore follow the same read contract.
function markReadIfViewing(id, unread, lastSeq) {
  if (!id || !(unread > 0)) return;
  // Visibility is intentionally looser than focus, which browser chrome and devtools can own.
  if (document.visibilityState !== "visible") return;
  if (!sessionViewOnScreen) return;
  postRead(id, lastSeq);
}

function detachedHint(session) {
  return session
    ? "Detached from " + displayName(session) + ". The agent keeps running."
    : "Terminal detached.";
}

function App() {
  const [sessions, setSessions] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [projects, setProjects] = useState([]);
  const [projectId, setProjectId] = useState(null);
  const [route, setRoute] = useState(() => parseRoute(window.location.pathname, window.location.search));
  const [currentVersion, setCurrentVersion] = useState("");
  const [activeId, setActiveId] = useState(null);
  const [attachedId, setAttachedId] = useState(null);
  const [pendingAction, setPendingAction] = useState(null);
  const [prefs, setPrefs] = useState(loadPrefs);
  const [dialog, setDialog] = useState(null);
  const [palette, setPalette] = useState(null);
  const [showDone, setShowDone] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(loadSidebarCollapsed);
  const [status, setStatus] = useState({ text: "", error: false });
  const [hint, setHint] = useState(SELECT_HINT);
  const [drawerOpen, setDrawerOpen] = useState(false);

  const onBoard = route.screen === SCREEN_TASKS || route.screen === SCREEN_TASK;
  sessionViewOnScreen = !onBoard;

  const openPalette = useCallback((mode = "leader") => setPalette({ mode: mode }), []);
  const closePalette = useCallback(() => setPalette(null), []);
  useEffect(() => { persistSidebarCollapsed(sidebarCollapsed); }, [sidebarCollapsed]);
  // subscribeToRoute covers both popstate and navigate().
  useEffect(() => subscribeToRoute(setRoute), []);

  const applyTasksBaseline = useCallback((rows) => {
    setTasks((current) => applyTasksSnapshot(current, rows));
  }, []);
  const applyTaskRow = useCallback((row) => {
    setTasks((current) => upsertTaskIfNewer(current, row));
  }, []);
  const applyTaskPatch = useCallback((msg) => {
    setTasks((current) => patchTaskIfNewer(current, msg));
  }, []);
  const applyTaskRemoved = useCallback((ref) => {
    setTasks((current) => removeTask(current, ref));
  }, []);
  const openTaskEntry = route.screen === SCREEN_TASK && route.id
    ? tasks.find((task) => task.ref === route.id) || null
    : null;

  const sessionsRef = useRef(sessions);
  sessionsRef.current = sessions;
  const activeRef = useRef(activeId);
  activeRef.current = activeId;
  // A generation counter closes the A→B→A hole when async flows conditionally auto-select.
  const selectionGenRef = useRef(0);
  const pendingRef = useRef(pendingAction);
  pendingRef.current = pendingAction;
  // Async completions may close only the dialog instance that submitted them.
  const dialogRef = useRef(dialog);
  dialogRef.current = dialog;
  const prefsRef = useRef(prefs);
  prefsRef.current = prefs;
  // Persisted revisions order racing HTTP and WebSocket updates; refs advance synchronously.
  const preferencesRevisionRef = useRef(prefs.revision);
  const serverPreferencesRef = useRef({
    basePath: prefs.basePath,
    groupingLevel: prefs.groupingLevel,
    revision: prefs.revision,
  });
  // Hold a notification target until a matching row exists.
  const deepLinkRef = useRef(deepLinkSessionId());
  const [sessionsReady, setSessionsReady] = useState(false);
  const sessionsReadyRef = useRef(false);
  // Announce each outage once so the reconnect loop does not flood the aria-live region.
  const disconnectAnnouncedRef = useRef(false);
  // A zero-delay boundary prevents Preact batching detach→same-id attach into no state change.
  const reattachIdRef = useRef(null);
  const reattachTimerRef = useRef(null);
  // The AbortController also owns the async liveness result, including repeated checks for one id.
  const reattachRequestRef = useRef(null);
  // Foregrounding or event-socket recovery grants one reattach attempt.
  const reattachAvailableRef = useRef(false);

  // Capture before xterm/forms; KeyboardEvent.code keeps the shortcut physical across layouts.
  useEffect(() => {
    const handler = (event) => {
      const opensPalette =
        (event.metaKey && event.code === "KeyK") ||
        (event.ctrlKey && event.shiftKey && event.code === "KeyK");
      // Safari also maps Command-period to stop-loading, so suppress it in capture phase.
      const togglesSidebar = event.metaKey && event.code === "Period";
      if ((!opensPalette && !togglesSidebar) || dialogRef.current) return;
      event.preventDefault();
      event.stopPropagation();
      if (togglesSidebar) {
        setSidebarCollapsed((collapsed) => !collapsed);
        return;
      }
      setPalette((current) => current
        ? { mode: current.mode === "search" ? "leader" : "search" }
        : { mode: "leader" });
    };
    document.addEventListener("keydown", handler, true);
    return () => document.removeEventListener("keydown", handler, true);
  }, []);

  const cancelReattach = useCallback(() => {
    reattachIdRef.current = null;
    reattachAvailableRef.current = false;
    const request = reattachRequestRef.current;
    reattachRequestRef.current = null;
    if (request) request.abort();
    if (reattachTimerRef.current !== null) {
      clearTimeout(reattachTimerRef.current);
      reattachTimerRef.current = null;
    }
  }, []);

  const scheduleReattach = useCallback(() => {
    if (document.visibilityState !== "visible" ||
        !reattachAvailableRef.current ||
        reattachTimerRef.current !== null) return;
    reattachTimerRef.current = setTimeout(async () => {
      reattachTimerRef.current = null;
      const id = reattachIdRef.current;
      // Preserve a grant that arrived before the queued terminal-close callback supplied its id.
      if (!id || document.visibilityState !== "visible") return;
      reattachAvailableRef.current = false;

      // The events socket may also be stale; fetch liveness and re-check local intent after awaiting.
      const controller = new AbortController();
      const previousRequest = reattachRequestRef.current;
      reattachRequestRef.current = controller;
      if (previousRequest) previousRequest.abort();
      const livenessTimeout = setTimeout(
        () => controller.abort(),
        REATTACH_LIVENESS_TIMEOUT_MS,
      );
      try {
        const s = await apiRequest(
          "/sessions/" + encodeURIComponent(id),
          { signal: controller.signal },
        );
        if (reattachRequestRef.current !== controller) return;
        if (reattachIdRef.current !== id) return;
        if (document.visibilityState !== "visible") return;
        if (activeRef.current !== id) {
          reattachIdRef.current = null;
          return;
        }
        // A pending control action temporarily owns the attachment decision; retain the candidate.
        if (pendingRef.current) return;
        if (!s || !isAliveState(s.state)) {
          reattachIdRef.current = null;
          setHint(deadHint(s && s.state));
          return;
        }

        reattachIdRef.current = null;
        setAttachedId(id);
        setHint(null);
      } catch (err) {
        if (reattachRequestRef.current !== controller) return;
        // Definite failures retire the candidate; transient failures await the next recovery grant.
        if (isDefiniteAnswer(err)) reattachIdRef.current = null;
        if (activeRef.current === id) setHint(detachedHint(null));
      } finally {
        clearTimeout(livenessTimeout);
        if (reattachRequestRef.current === controller) reattachRequestRef.current = null;
      }
    }, 0);
  }, []);

  const say = useCallback((text, error) => setStatus({ text: text, error: !!error }), []);

  // Project names are not sent over /events, so refresh them on mount and board entry.
  const reloadProjects = useCallback(async () => {
    try {
      const response = await fetchProjects();
      const rows = Array.isArray(response)
        ? response
        : (response && Array.isArray(response.projects) ? response.projects : []);
      setProjects(rows);
      return rows;
    } catch (e) {
      say("Could not load projects: " + errorMessage(e), true);
      return null;
    }
  }, [say]);

  useEffect(() => { reloadProjects(); }, [reloadProjects]);

  useEffect(() => {
    if (projects.length === 0) return;
    setProjectId((current) =>
      current && projects.some((project) => project.id === current) ? current : projects[0].id);
  }, [projects]);

  const selectProject = useCallback((id) => {
    setProjectId(id);
    setDrawerOpen(false);
  }, []);

  const projectCreated = useCallback(async (created) => {
    const rows = await reloadProjects();
    if (created && created.id && rows && rows.some((project) => project.id === created.id)) {
      setProjectId(created.id);
    }
  }, [reloadProjects]);

  const applyServerPreferences = useCallback((raw) => {
    const next = sanitizeServerPreferences(raw);
    if (!next || next.revision < preferencesRevisionRef.current) return false;
    preferencesRevisionRef.current = next.revision;
    serverPreferencesRef.current = next;
    setPrefs((current) => Object.assign({}, current, next));
    return true;
  }, []);

  // The submitting dialog may have been dismissed and replaced while its request was in flight.
  const closeDialogFrom = useCallback((submitted) => {
    setDialog((current) => (current === submitted ? null : current));
  }, []);

  const activeSession = sessions.find((s) => s.id === activeId) || null;

  const showSession = useCallback((session) => {
    selectionGenRef.current += 1;
    cancelReattach();
    setActiveId(session.id);
    setDrawerOpen(false);
    // The route is the owner of both the visible screen and selected session.
    navigate(sessionPath(session.id));
    if (isAliveState(session.state)) {
      reattachAvailableRef.current = true;
      setAttachedId(session.id);
      setHint(null);
    } else {
      setAttachedId(null);
      setHint(deadHint(session.state));
    }
    // Newly created rows may not have reached sessionsRef yet.
    markReadIfViewing(session.id, session.unread, session.lastSeq);
  }, [cancelReattach]);

  const selectSession = useCallback((id) => {
    const session = sessionsRef.current.find((s) => s.id === id);
    if (session) showSession(session);
  }, [showSession]);

  // Route targets wait for their row. A bare "/" intentionally preserves the current terminal.
  const routeSessionId = route.screen === SCREEN_SESSIONS ? route.id : null;
  useEffect(() => {
    if (!routeSessionId || routeSessionId === activeId) return;
    const target = sessions.find((s) => s.id === routeSessionId);
    if (!target) return;
    // Retire the retained target so a later duplicate row cannot re-select it.
    if (deepLinkRef.current === routeSessionId) deepLinkRef.current = null;
    showSession(target);
  }, [routeSessionId, sessions, activeId, showSession]);

  useEffect(() => {
    if (onBoard) reloadProjects();
  }, [onBoard, reloadProjects]);

  // Apply a task route's project once per ref so later manual project selection remains authoritative.
  const appliedTaskProjectRef = useRef(null);
  const openTaskRef = route.screen === SCREEN_TASK ? route.id : null;
  useEffect(() => {
    if (!openTaskRef) { appliedTaskProjectRef.current = null; return; }
    if (appliedTaskProjectRef.current === openTaskRef) return;
    const entry = tasks.find((task) => task.ref === openTaskRef);
    if (!entry) return;
    appliedTaskProjectRef.current = openTaskRef;
    setProjectId(entry.project);
  }, [openTaskRef, tasks]);

  // Returning from the board must retry mark-read even if the session emitted no new frame.
  useEffect(() => {
    if (onBoard) return;
    const s = sessionsRef.current.find((x) => x.id === activeRef.current);
    if (s) markReadIfViewing(s.id, s.unread, s.lastSeq);
  }, [onBoard]);

  const applySessionsSnapshot = useCallback((rows) => {
    // Reconnect snapshots are the only attention transition carrier for changes made while offline.
    const prev = sessionsRef.current;
    for (const row of rows) {
      const prevRow = prev.find((s) => s.id === row.id);
      if (prevRow && !prevRow.needsAttention && row.needsAttention) notifyAttention(prevRow);
    }
    // Reconnect snapshots are authoritative, including deletions.
    setSessions(rows);
    const ids = new Set(rows.map((s) => s.id));
    setActiveId((id) => (id && !ids.has(id) ? null : id));
    setAttachedId((id) => (id && !ids.has(id) ? null : id));
    pruneReadPosters(ids);
    if (reattachIdRef.current && !ids.has(reattachIdRef.current)) cancelReattach();
    const wanted = deepLinkRef.current;
    if (wanted) {
      const target = rows.find((s) => s.id === wanted);
      if (target) {
        deepLinkRef.current = null;
        clearDeepLink();
        showSession(target);
      }
    }
    // Judge unread from the frame; sessionsRef has not caught up with setSessions yet.
    const active = rows.find((s) => s.id === activeRef.current);
    if (active) markReadIfViewing(active.id, active.unread, active.lastSeq);
    disconnectAnnouncedRef.current = false;
    if (!sessionsReadyRef.current) {
      sessionsReadyRef.current = true;
      setSessionsReady(true);
      // Do not repeat the routine count into the aria-live region after reconnects.
      say(rows.length + " session(s).");
    }
  }, [cancelReattach, say, showSession]);

  const applySessionRow = useCallback((row) => {
    const prevRow = sessionsRef.current.find((s) => s.id === row.id);
    if (prevRow && !prevRow.needsAttention && row.needsAttention) notifyAttention(prevRow);
    setSessions((prev) => upsertIfNewer(prev, row));
    if (deepLinkRef.current === row.id) {
      deepLinkRef.current = null;
      clearDeepLink();
      showSession(row);
      return;
    }
    if (row.id === activeRef.current) markReadIfViewing(row.id, row.unread, row.lastSeq);
  }, [showSession]);

  const applySessionPatch = useCallback((msg) => {
    const prevSession = sessionsRef.current.find((s) => s.id === msg.sessionId);
    if (!prevSession) return;
    if (!prevSession.needsAttention && msg.needsAttention) notifyAttention(prevSession);
    setSessions((prev) => patchIfNewer(prev, msg));
    // Judge unread from the frame; sessionsRef has not caught up with setSessions yet.
    if (msg.sessionId === activeRef.current) {
      markReadIfViewing(msg.sessionId, msg.unread, msg.lastSeq);
    }
  }, []);

  // Targeted GETs merge by revision and return null so callers decide how to surface misses.
  const fetchSessionRow = useCallback(async (id) => {
    try {
      const row = await apiRequest("/sessions/" + encodeURIComponent(id));
      if (row && row.id) {
        applySessionRow(row);
        return row;
      }
    } catch (_) {}
    return null;
  }, [applySessionRow]);
  const fetchSessionRowRef = useRef(fetchSessionRow);
  fetchSessionRowRef.current = fetchSessionRow;

  // Revision ordering prevents this initial GET from rolling back a concurrent save or WS update.
  // It is also the installed app's first-load 401 gate; replace avoids a back-button loop.
  useEffect(() => {
    let stopped = false;
    apiRequest("/preferences")
      .then((value) => { if (!stopped) applyServerPreferences(value); })
      .catch((e) => {
        if (stopped) return;
        if (isUnauthenticated(e)) {
          window.location.replace(AUTH_PATH);
          return;
        }
        say("Could not load preferences: " + errorMessage(e), true);
      });
    return () => { stopped = true; };
  }, [applyServerPreferences, say]);

  useEffect(() => {
    let stopped = false;
    apiRequest("/version")
      .then((info) => {
        if (!stopped && info && typeof info.version === "string") {
          setCurrentVersion(info.version);
        }
      })
      .catch(() => {});
    return () => { stopped = true; };
  }, []);

  // Dispatch through a ref to keep one socket while reconnect snapshots restore the baseline.
  const onSessionsFrame = useCallback((msg) => {
    if (msg.type === "sessions_snapshot") applySessionsSnapshot(msg.sessions);
    else if (msg.type === "session_row") applySessionRow(msg.session);
    else if (msg.type === "session_update") applySessionPatch(msg);
    else if (msg.type === "tasks_snapshot") applyTasksBaseline(msg.tasks);
    else if (msg.type === "task_row") applyTaskRow(msg.task);
    else if (msg.type === "task_update") applyTaskPatch(msg.task);
    else if (msg.type === "task_removed") applyTaskRemoved(msg.ref);
  }, [
    applySessionsSnapshot, applySessionRow, applySessionPatch,
    applyTasksBaseline, applyTaskRow, applyTaskPatch, applyTaskRemoved,
  ]);
  const sessionsFrameRef = useRef(onSessionsFrame);
  sessionsFrameRef.current = onSessionsFrame;
  // Keeping the socket stable also preserves whether a later open is a recovery.
  const scheduleReattachRef = useRef(scheduleReattach);
  scheduleReattachRef.current = scheduleReattach;
  useEffect(() => {
    let socket = null;
    let timer = null;
    let stopped = false;
    let opened = false;

    const connect = () => {
      if (stopped) return;
      try {
        socket = new WebSocket(wsUrl("/events"));
      } catch (e) {
        // The list has no HTTP fallback, so keep reconnecting.
        say("events WS error: " + e, true);
        timer = setTimeout(connect, 2000);
        return;
      }
      socket.onopen = () => {
        if (opened) {
          // Event-socket recovery grants a fresh owned terminal liveness check.
          reattachAvailableRef.current = true;
          scheduleReattachRef.current();
        }
        opened = true;
      };
      socket.onmessage = (ev) => {
        let msg;
        try { msg = JSON.parse(ev.data); } catch (_) { return; }
        if (!msg) return;
        if (msg.type === "preferences_update") {
          applyServerPreferences(msg);
          return;
        }
        sessionsFrameRef.current(msg);
      };
      socket.onclose = () => {
        if (stopped) return;
        if (!disconnectAnnouncedRef.current) {
          disconnectAnnouncedRef.current = true;
          say("Daemon connection lost — reconnecting…", true);
        }
        timer = setTimeout(connect, 2000);
      };
      socket.onerror = () => {};
    };

    connect();
    return () => {
      stopped = true;
      clearTimeout(timer);
      if (socket) {
        socket.onclose = null;
        try { socket.close(); } catch (_) {}
      }
    };
  }, [applyServerPreferences, say]);

  // Foregrounding retries mark-read after hidden-tab updates were deliberately suppressed.
  useEffect(() => {
    const onVisibilityChange = () => {
      const s = sessionsRef.current.find((x) => x.id === activeRef.current);
      if (s) markReadIfViewing(s.id, s.unread, s.lastSeq);
    };
    document.addEventListener("visibilitychange", onVisibilityChange);
    return () => document.removeEventListener("visibilitychange", onVisibilityChange);
  }, []);

  // The service worker sends a session id when a notification focuses an existing page.
  useLayoutEffect(() => {
    if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return undefined;
    const onMessage = (event) => {
      const msg = event.data;
      if (!msg || msg.type !== "select-session" || !msg.sessionId) return;
      if (sessionsRef.current.some((session) => session.id === msg.sessionId)) {
        // A newer tap supersedes any retained target whose row may arrive later.
        deepLinkRef.current = null;
        clearDeepLink();
        selectSession(msg.sessionId);
        return;
      }
      // A backgrounded page may be stale; retain the target while fetching its row.
      deepLinkRef.current = msg.sessionId;
      fetchSessionRowRef.current(msg.sessionId);
    };
    navigator.serviceWorker.addEventListener("message", onMessage);
    return () => navigator.serviceWorker.removeEventListener("message", onMessage);
  }, [selectSession]);

  // Mobile suspension may drop the terminal socket. Foregrounding grants one ordered reattach attempt.
  useEffect(() => {
    const reconnectWhenVisible = () => {
      const visible = document.visibilityState === "visible";
      reattachAvailableRef.current = visible;
      if (!visible) {
        if (reattachTimerRef.current !== null) {
          clearTimeout(reattachTimerRef.current);
          reattachTimerRef.current = null;
        }
        const request = reattachRequestRef.current;
        reattachRequestRef.current = null;
        if (request) request.abort();
        return;
      }
      scheduleReattach();
    };

    document.addEventListener("visibilitychange", reconnectWhenVisible);
    return () => {
      document.removeEventListener("visibilitychange", reconnectWhenVisible);
      cancelReattach();
    };
  }, [cancelReattach, scheduleReattach]);

  const startSession = useCallback(async (body) => {
    const submittedDialog = dialogRef.current;
    // Auto-select only if no selection event occurred during the request.
    const selectionAtSubmit = selectionGenRef.current;
    let created;
    try {
      created = await apiRequest("/sessions", {
        method: "POST",
        body: JSON.stringify(body),
      });
    } catch (e) {
      // Late failures surface globally if the submitting form has unmounted.
      if (dialogRef.current === submittedDialog) throw e;
      say("Could not start session: " + errorMessage(e), true);
      return;
    }
    setSessions((prev) => upsertIfNewer(prev, created));
    closeDialogFrom(submittedDialog);
    say("Started " + displayName(created) + ".");
    if (selectionGenRef.current === selectionAtSubmit) showSession(created);
  }, [closeDialogFrom, say, showSession]);

  // Import and optional resume are serialized as one action. HTTP rows merge by revision, targeted
  // GETs decide attachment from fresh state, and generation guards prevent late auto-selection.
  // Registration success closes the dialog even when its follow-up resume fails.
  const importSession = useCallback(async (body, registerOnly) => {
    if (pendingRef.current) {
      throw new Error("Another action is still in progress — try again in a moment.");
    }
    const submittedDialog = dialogRef.current;
    const selectionAtSubmit = selectionGenRef.current;
    const selectionUnmoved = () => selectionGenRef.current === selectionAtSubmit;
    setPendingAction("import");
    try {
      let created;
      try {
        created = await apiRequest("/sessions/import", {
          method: "POST",
          body: JSON.stringify(body),
        });
      } catch (e) {
        if (dialogRef.current === submittedDialog) throw e;
        say(errorMessage(e), true);
        return;
      }
      // Fetch after commit; fall back to the committed 201 row if the read is unavailable.
      const fetched = await fetchSessionRow(created.id);
      const registered = fetched || created;
      if (!fetched) setSessions((prev) => upsertIfNewer(prev, created));
      closeDialogFrom(submittedDialog);
      if (registerOnly) {
        if (fetched) say("Imported " + displayName(registered) + " — registered only.");
        if (selectionUnmoved()) showSession(registered);
        return;
      }
      try {
        const resumedDto = await apiRequest(
          "/sessions/" + encodeURIComponent(created.id) + "/resume",
          { method: "POST" },
        );
        // Re-read after resume so an immediate exit cannot attach using stale live state.
        const freshRow = await fetchSessionRow(created.id);
        // The resume DTO is the best fallback; the pre-resume row would suppress attachment.
        const row = freshRow || (resumedDto && resumedDto.id ? resumedDto : registered);
        if (!freshRow && resumedDto && resumedDto.id) setSessions((prev) => upsertIfNewer(prev, resumedDto));
        if (freshRow) say("Imported and resumed " + displayName(row) + ".");
        if (selectionUnmoved()) showSession(row);
      } catch (e) {
        const after = await fetchSessionRow(created.id);
        if (selectionUnmoved()) showSession(after || registered);
        say("Imported, but resume failed: " + errorMessage(e), true);
      }
    } finally {
      setPendingAction(null);
    }
  }, [closeDialogFrom, fetchSessionRow, say, showSession]);

  const controlSession = useCallback(async (action, id) => {
    const s = sessionsRef.current.find((x) => x.id === (id || activeRef.current));
    if (!s) return;
    if (pendingRef.current) {
      say("Another action is still in progress — try again in a moment.", true);
      return;
    }
    if (action === "stop" &&
        !window.confirm("Stop " + displayName(s) + "? The conversation can be resumed later.")) {
      return;
    }
    if (action === "done" &&
        !window.confirm("Mark " + displayName(s) + " done? This stops the agent and hides the session.")) {
      return;
    }
    if (action === "stop" || action === "done" || action === "resume") cancelReattach();

    setPendingAction(action);
    say(capitalize(action) + " in progress…");
    try {
      const updated = await apiRequest(
        "/sessions/" + encodeURIComponent(s.id) + "/" + encodeURIComponent(action),
        { method: "POST" },
      );
      if (updated && updated.id) {
        setSessions((prev) => upsertIfNewer(prev, updated));
      }
      if (action === "stop" || action === "done") {
        if (s.id === activeRef.current) setAttachedId(null);
        setHint(action === "done"
          ? "Marked done. Find it under “Show done”."
          : "Session stopped. Resume it to continue.");
      } else if (action === "resume") {
        reattachAvailableRef.current = true;
        // Do not attach over a newer selection or erase the hint that selection installed.
        if (s.id === activeRef.current) {
          setAttachedId(s.id);
          setHint(null);
        }
      }
      say(capitalize(action) + " completed for " + displayName(s) + ".");
    } catch (e) {
      say(capitalize(action) + " failed: " + errorMessage(e), true);
    } finally {
      setPendingAction(null);
    }
  }, [cancelReattach, say]);

  // Local attach/detach must not race actions that can rewrite attachment state.
  const attach = useCallback(() => {
    if (!activeRef.current) return;
    if (affectsAttachment(pendingRef.current)) {
      say("Another action is still in progress — try again in a moment.", true);
      return;
    }
    cancelReattach();
    reattachAvailableRef.current = true;
    setAttachedId(activeRef.current);
    setHint(null);
  }, [cancelReattach, say]);

  const detach = useCallback(() => {
    if (affectsAttachment(pendingRef.current)) {
      say("Another action is still in progress — try again in a moment.", true);
      return;
    }
    const s = sessionsRef.current.find((x) => x.id === activeRef.current);
    cancelReattach();
    setAttachedId(null);
    setHint(detachedHint(s));
  }, [cancelReattach, say]);

  // Report async copy results outside the palette because its aria-live region unmounts immediately.
  const copyTmuxCommand = useCallback(async () => {
    const s = sessionsRef.current.find((x) => x.id === activeRef.current);
    const command = s && isAliveState(s.state) && s.tmuxSession
      ? tmuxAttachCommand(s.tmuxSession)
      : "";
    if (!command) {
      say("Could not copy tmux command: select a live session with a tmux name.", true);
      return;
    }
    try {
      await writeClipboard(command);
      say("Tmux command copied to clipboard.");
    } catch (_) {
      say("Could not copy the tmux command.", true);
    }
  }, [say]);

  const onTerminalClosed = useCallback((id) => {
    const s = sessionsRef.current.find((session) => session.id === id);
    reattachIdRef.current = id;
    setAttachedId((current) => (current === id ? null : current));
    if (activeRef.current === id) setHint(detachedHint(s));
    // A foreground grant may precede this queued close callback; reschedule once its id is known.
    if (document.visibilityState === "visible") scheduleReattach();
  }, [scheduleReattach]);

  // Dialogs can close or remount while saving, so component-local busy state cannot serialize PUTs.
  const prefsSaveInFlightRef = useRef(false);

  const savePreferences = useCallback(async (next) => {
    if (prefsSaveInFlightRef.current) {
      throw new Error("A preferences save is already in progress — try again in a moment.");
    }
    prefsSaveInFlightRef.current = true;
    const submittedDialog = dialogRef.current;
    // Form revision distinguishes a remounted PreferencesDialog when routing late failures.
    const revisionAtSubmit = prefsRef.current.revision;
    try {
      const saved = await apiRequest("/preferences", {
        method: "PUT",
        body: JSON.stringify({
          basePath: next.basePath,
          groupingLevel: next.groupingLevel,
        }),
      });
      // An unreadable 2xx body cannot establish what the daemon committed.
      if (!sanitizeServerPreferences(saved)) {
        throw new Error("the daemon answered the save with an unreadable preferences payload");
      }
      // A WS echo may beat this response: equal revision is this save, while strictly newer external
      // state wins and keeps the refreshed form open.
      const applied = applyServerPreferences(saved);
      persistTerminalFontSize(next.terminalFontSize);
      persistTerminalUnicode(next.terminalUnicode);
      setPrefs((current) => Object.assign({}, current, {
        terminalFontSize: next.terminalFontSize,
        terminalUnicode: next.terminalUnicode,
      }));
      if (!applied) {
        say("Preferences were saved, but newer settings arrived. Review the current values.");
        return;
      }
      // Keep the apply decision and close in the same turn.
      closeDialogFrom(submittedDialog);
      const current = serverPreferencesRef.current;
      say(current.basePath.length > 0
        ? "Grouping by " + current.basePath + " (level " + current.groupingLevel + ")."
        : "Grouping off — no base path set.");
    } catch (e) {
      // Late failures surface globally if the submitting form has unmounted.
      if (dialogRef.current === submittedDialog && prefsRef.current.revision === revisionAtSubmit) throw e;
      say("Could not save preferences: " + errorMessage(e), true);
    } finally {
      prefsSaveInFlightRef.current = false;
    }
  }, [applyServerPreferences, closeDialogFrom, say]);

  const openNewSession = useCallback((cwd, initialMode = "start", initialAgent = "", taskRef = null) => {
    const selected = sessionsRef.current.find((x) => x.id === activeRef.current);
    setDialog({
      kind: "new",
      cwd: cwd || (selected && selected.cwd) || prefsRef.current.basePath,
      initialMode: initialMode,
      initialAgent: initialAgent,
      taskRef: taskRef,
    });
  }, []);
  const openImportSession = useCallback(() => openNewSession(null, "import"), [openNewSession]);
  const openFreeTerminal = useCallback(
    () => openNewSession(null, "start", "shell"),
    [openNewSession],
  );
  const startSessionForTask = useCallback(
    (cwd, taskRef) => openNewSession(cwd, "start", "", taskRef),
    [openNewSession],
  );

  const openBoard = useCallback(() => navigate(routePath({ screen: SCREEN_TASKS, id: null })), []);
  // Preserve selection and attachment when leaving the board; avoid showSession's side effects.
  const openSessions = useCallback(() => {
    const id = activeRef.current;
    navigate(routePath({ screen: SCREEN_SESSIONS, id: id }));
  }, []);
  // Counters let repeated commands retrigger while the board remains mounted.
  const [newTaskRequest, setNewTaskRequest] = useState(0);
  const newTask = useCallback(() => {
    navigate(routePath({ screen: SCREEN_TASKS, id: null }));
    setNewTaskRequest((n) => n + 1);
  }, []);
  const [newProjectRequest, setNewProjectRequest] = useState(0);
  const newProject = useCallback(() => {
    navigate(routePath({ screen: SCREEN_TASKS, id: null }));
    setNewProjectRequest((n) => n + 1);
  }, []);
  // Reset before remount so stale requests cannot reopen forms on a later board visit.
  useEffect(() => {
    if (!onBoard) {
      setNewTaskRequest(0);
      setNewProjectRequest(0);
    }
  }, [onBoard]);
  const openSessionTask = useCallback(() => {
    const selected = sessionsRef.current.find((x) => x.id === activeRef.current);
    if (selected && selected.taskRef) navigate(taskPath(selected.taskRef));
  }, []);

  const closeDrawer = useCallback(() => setDrawerOpen(false), []);
  const toggleDrawer = useCallback(() => setDrawerOpen((open) => !open), []);
  const toggleSidebar = useCallback(() => setSidebarCollapsed((collapsed) => !collapsed), []);

  const closeDialog = useCallback(() => setDialog(null), []);
  const openPrefs = useCallback(() => setDialog({ kind: "prefs" }), []);
  const openHelp = useCallback(() => setDialog({ kind: "help" }), []);
  const openPhone = useCallback(() => setDialog({ kind: "phone" }), []);
  const openUpload = useCallback(() => {
    const selected = sessionsRef.current.find((session) => session.id === activeRef.current);
    if (selected) setDialog({ kind: "upload", session: selected });
  }, []);

  const interrupt = useCallback(() => controlSession("interrupt"), [controlSession]);
  const resume = useCallback(() => controlSession("resume"), [controlSession]);
  const stop = useCallback(() => controlSession("stop"), [controlSession]);
  const done = useCallback(() => controlSession("done"), [controlSession]);
  const restore = useCallback((id) => controlSession("undone", id), [controlSession]);
  const toggleShowDone = useCallback(() => setShowDone((shown) => !shown), []);
  const changePaletteMode = useCallback((mode) => {
    setPalette((current) => current ? { mode: mode } : current);
  }, []);

  const commands = buildCommands({
    sessions: sessions,
    activeSession: activeSession,
    attachedId: attachedId,
    pendingAction: pendingAction,
    onBoard: onBoard,
    actions: {
      selectSession: selectSession,
      interrupt: interrupt,
      resume: resume,
      attach: attach,
      detach: detach,
      stop: stop,
      done: done,
      copyTmux: copyTmuxCommand,
      uploadFiles: openUpload,
      newSession: () => openNewSession(null),
      importSession: openImportSession,
      freeTerminal: openFreeTerminal,
      toggleShowDone: toggleShowDone,
      help: openHelp,
      phone: openPhone,
      preferences: openPrefs,
      openBoard: openBoard,
      openSessions: openSessions,
      newTask: newTask,
      newProject: newProject,
      openSessionTask: openSessionTask,
    },
  });

  return html`
    ${palette && html`
      <${CommandPalette}
        commands=${commands}
        mode=${palette.mode}
        onModeChange=${changePaletteMode}
        onClose=${closePalette}
      />`}
    ${""}
    ${drawerOpen && html`
      <button type="button" class="drawer-scrim" aria-label="Close the sidebar"
              onClick=${closeDrawer}></button>`}
    ${""}
    <${Sidebar}
      screen=${onBoard ? SCREEN_TASKS : SCREEN_SESSIONS}
      sessions=${sessions}
      tasks=${tasks}
      projects=${projects}
      projectId=${projectId}
      activeId=${activeId}
      prefs=${prefs}
      status=${status}
      currentVersion=${currentVersion}
      drawerOpen=${drawerOpen}
      collapsed=${sidebarCollapsed}
      showDone=${showDone}
      sessionsReady=${sessionsReady}
      onSelect=${selectSession}
      onSelectProject=${selectProject}
      onNewSession=${openNewSession}
      onNewProject=${newProject}
      onOpenPrefs=${openPrefs}
      onRestore=${restore}
      onCloseDrawer=${closeDrawer}
      onToggleShowDone=${toggleShowDone}
    />
    ${""}
    ${onBoard ? html`
      <${Board}
        tasks=${tasks}
        sessions=${sessions}
        route=${route}
        projects=${projects}
        projectId=${projectId}
        basePath=${prefs.basePath}
        newTaskRequest=${newTaskRequest}
        newProjectRequest=${newProjectRequest}
        drawerOpen=${drawerOpen}
        sidebarCollapsed=${sidebarCollapsed}
        onTaskRow=${applyTaskRow}
        onProjectCreated=${projectCreated}
        onToggleDrawer=${toggleDrawer}
        onToggleSidebar=${toggleSidebar}
        onOpenPalette=${openPalette}
        onAnnounce=${say}
      />
      ${route.screen === SCREEN_TASK && html`
        <${TaskDetail} taskRef=${route.id} entry=${openTaskEntry} sessions=${sessions}
                       onTaskRow=${applyTaskRow} onTaskRemoved=${applyTaskRemoved}
                       onStartSession=${startSessionForTask} onAnnounce=${say} />`}
      <p id="board-status" class=${"status-line board-status" + (status.error ? " error" : "")}
         role="status" aria-live="polite">${status.text}</p>
    ` : html`
      <${TerminalPane}
        session=${activeSession}
        tasks=${tasks}
        attachedId=${attachedId}
        terminalFontSize=${prefs.terminalFontSize}
        terminalUnicode=${prefs.terminalUnicode}
        hint=${hint}
        drawerOpen=${drawerOpen}
        sidebarCollapsed=${sidebarCollapsed}
        onToggleDrawer=${toggleDrawer}
        onToggleSidebar=${toggleSidebar}
        onOpenPalette=${openPalette}
        onTerminalClosed=${onTerminalClosed}
      />
    `}
    ${dialog && dialog.kind === "new" && html`
      <${NewSessionDialog} initialCwd=${dialog.cwd} initialMode=${dialog.initialMode}
                           initialAgent=${dialog.initialAgent}
                           initialTaskRef=${dialog.taskRef}
                           basePath=${prefs.basePath}
                           onStart=${startSession} onImport=${importSession} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "upload" && html`
      <${UploadFilesDialog} session=${dialog.session} onClose=${closeDialog} />`}
    ${/* Remount on server revision so an open draft cannot overwrite newer committed values. */ ""}
    ${dialog && dialog.kind === "prefs" && html`
      <${PreferencesDialog} key=${prefs.revision} prefs=${prefs} sessions=${sessions}
                            onSave=${savePreferences} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "help" && html`<${HelpDialog} onClose=${closeDialog} />`}
    ${dialog && dialog.kind === "phone" && html`<${PhoneDialog} onClose=${closeDialog} />`}
  `;
}

// WebKit/iOS may report installed mode as fullscreen or only through navigator.standalone.
const appRoot = document.getElementById("app");
const installedApp =
  window.matchMedia("(display-mode: standalone)").matches ||
  window.matchMedia("(display-mode: fullscreen)").matches ||
  window.navigator.standalone === true;
appRoot.classList.toggle("installed-app", installedApp);
render(html`<${App} />`, appRoot);
