package io.kotgent.adapter.codex

/**
 * Generates Codex's per-launch hook script and `-c` config. User-level hook files would affect every
 * Codex session, while `-c` is session-scoped. The secret stays in a `0600` curl header file.
 */
object CodexHookConfig {
    const val INGRESS_PATH: String = "/hooks/codex"

    const val HOOK_TOKEN_HEADER: String = "X-Kotgent-Hook-Token"

    const val TMUX_PANE_HEADER: String = "X-Kotgent-Tmux-Pane"

    const val HOOK_EVENT_HEADER: String = "X-Kotgent-Hook-Event"

    const val SHELL_INTERPRETER: String = "/bin/sh"

    const val USER_PROMPT_SUBMIT: String = "UserPromptSubmit"
    const val POST_TOOL_USE: String = "PostToolUse"
    const val PERMISSION_REQUEST: String = "PermissionRequest"
    const val STOP: String = "Stop"
    const val SESSION_START: String = "SessionStart"
    const val SESSION_END: String = "SessionEnd"

    /** Hooks that do not change the shared state machine are intentionally omitted. */
    val HOOK_EVENTS: List<String> = listOf(
        USER_PROMPT_SUBMIT, POST_TOOL_USE, PERMISSION_REQUEST, STOP, SESSION_START, SESSION_END,
    )

    fun ingressUrl(port: Int): String = "http://127.0.0.1:$port$INGRESS_PATH"

    fun headerFileContent(token: String): String = "$HOOK_TOKEN_HEADER: $token\n"

    fun hookScript(port: Int, headerFilePath: String): String = buildString {
        appendLine("#!/bin/sh")
        appendLine("# Generated by kotgent — do not edit. Invoked by codex hooks as: <script> <EventName>")
        appendLine("exec curl -sS -o /dev/null -X POST \\")
        appendLine("  ${shSingleQuote(ingressUrl(port) + "?event=")}\"\$1\" \\")
        appendLine("  -H ${shSingleQuote("@$headerFilePath")} \\")
        // These values must expand when Codex invokes the hook.
        appendLine("  -H \"$TMUX_PANE_HEADER: \$TMUX_PANE\" \\")
        appendLine("  -H \"$HOOK_EVENT_HEADER: \$1\" \\")
        appendLine("  -H ${shSingleQuote("Content-Type: application/json")} \\")
        appendLine("  --data-binary @-")
    }

    fun hooksToml(scriptPath: String): String = buildString {
        append("hooks={")
        HOOK_EVENTS.forEachIndexed { index, event ->
            if (index > 0) append(",")
            append(event).append("=[{")
            if (event == POST_TOOL_USE) append("matcher=\"*\",")
            append("hooks=[{type=\"command\",command=")
            // An explicit interpreter lets the private script remain non-executable and mode 0600.
            append(tomlString("$SHELL_INTERPRETER ${shSingleQuote(scriptPath)} $event"))
            append("}]}]")
        }
        append("}")
    }

    private fun tomlString(s: String): String = buildString(s.length + 2) {
        append('"')
        for (c in s) {
            when (c) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> if (c < ' ') append("\\u").append(c.code.toString(16).padStart(4, '0')) else append(c)
            }
        }
        append('"')
    }

    private fun shSingleQuote(s: String): String = "'" + s.replace("'", "'\\''") + "'"
}
