package io.kotgent.crypto

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse

/**
 * Base64url against published vectors. Like [sha256] this is a from-scratch implementation, so it gets
 * checked the only way an encoder can be: against strings produced independently — the RFC 4648 §10 test
 * vectors, and (for the byte values no ASCII vector reaches) values generated by a separate base64url
 * implementation.
 *
 * Two properties carry the whole feature. The **tail lengths** — a 1-byte remainder must yield 2
 * characters and a 2-byte remainder 3, with the leftover bits shifted into the next sextet rather than
 * dropped — and the **alphabet**, because a stray `+`, `/` or `=` reaching a push service is rejected at
 * the far end (RFC 7515 forbids padding) where the failure looks like "Apple said 400", not "the encoder
 * is wrong".
 */
class Base64UrlTest {

    @Test
    fun matchesTheRfc4648TestVectors() {
        // RFC 4648 §10, minus the '=' padding this variant never emits.
        assertEquals("", base64Url("".encodeToByteArray()), "the empty input encodes to the empty string")
        assertEquals("Zg", base64Url("f".encodeToByteArray()))
        assertEquals("Zm8", base64Url("fo".encodeToByteArray()))
        assertEquals("Zm9v", base64Url("foo".encodeToByteArray()))
        assertEquals("Zm9vYg", base64Url("foob".encodeToByteArray()))
        assertEquals("Zm9vYmE", base64Url("fooba".encodeToByteArray()))
        assertEquals("Zm9vYmFy", base64Url("foobar".encodeToByteArray()))
    }

    @Test
    fun encodesEveryPaddingRemainderLength() {
        // The three residues of size % 3: a full group, a 1-byte tail (2 chars) and a 2-byte tail (3).
        assertEquals(4, base64Url(byteArrayOf(0, 0, 0)).length, "a whole 3-byte group is 4 characters")
        assertEquals("AAAA", base64Url(byteArrayOf(0, 0, 0)))
        assertEquals("AA", base64Url(byteArrayOf(0)), "a 1-byte tail is 2 characters, not 4")
        assertEquals("AAA", base64Url(byteArrayOf(0, 0)), "a 2-byte tail is 3 characters, not 4")
        assertEquals("_w", base64Url(byteArrayOf(0xff.toByte())), "the 1-byte tail keeps its low bits")
        assertEquals("-_8", base64Url(byteArrayOf(0xfb.toByte(), 0xff.toByte())))
        assertEquals("-_A", base64Url(byteArrayOf(0xfb.toByte(), 0xf0.toByte())))
    }

    @Test
    fun usesTheUrlSafeAlphabetForHighBitBytes() {
        // Indices 62 and 63 are the only characters that differ from standard base64, and they are
        // unreachable from ASCII text — 0xff/0xfb are what produce them.
        assertEquals("____", base64Url(byteArrayOf(-1, -1, -1)), "index 63 is '_', never '/'")
        assertEquals("-_8", base64Url(byteArrayOf(0xfb.toByte(), 0xff.toByte())), "index 62 is '-', never '+'")
    }

    @Test
    fun neverEmitsPlusSlashOrPadding() {
        val allBytes = ByteArray(256) { it.toByte() }
        val encoded = base64Url(allBytes)
        assertFalse(encoded.contains('+'), "'+' would break a URL and a JWT segment")
        assertFalse(encoded.contains('/'), "'/' would break a URL and a JWT segment")
        assertFalse(encoded.contains('='), "padding is forbidden by RFC 7515 §2")
        for (size in 0..64) {
            // Every tail length, not just the alphabet: '=' can only ever appear on a partial group.
            assertFalse(base64Url(ByteArray(size) { 0xff.toByte() }).contains('='), "padding for $size bytes")
        }
    }

    @Test
    fun handlesEveryByteValue() {
        // Text vectors never exercise the high bit, which is exactly where a missing `and 0xff` on a
        // signed Kotlin Byte sign-extends and corrupts the sextets.
        assertEquals(
            "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0-P0" +
                "BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn" +
                "-AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq-wsbKztLW2t7i5uru8vb" +
                "6_wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t_g4eLj5OXm5-jp6uvs7e7v8PHy8_T19vf4-fr7_P" +
                "3-_w",
            base64Url(ByteArray(256) { it.toByte() }),
        )
    }

    @Test
    fun encodesTheShapeVapidActuallySends() {
        // The application server key is a 65-byte uncompressed P-256 point (0x04 || X || Y): 65 % 3 == 2,
        // so it lands on the 3-character tail — 87 characters, the length every Web Push client expects.
        val point = ByteArray(65) { if (it == 0) 0x04 else (it - 1).toByte() }
        val encoded = base64Url(point)
        assertEquals(87, encoded.length, "65 bytes is 21 full groups plus a 2-byte tail")
        assertEquals(
            "BAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj8",
            encoded,
        )
    }

    @Test
    fun outputLengthIsFourCharactersPerThreeBytesRoundedUp() {
        for (size in 0..40) {
            val expected = (size + 2) / 3 * 4 - listOf(0, 2, 1)[size % 3]
            assertEquals(expected, base64Url(ByteArray(size)).length, "encoded length for $size bytes")
        }
    }
}
