package io.kotgent.adapter.junie

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.addJsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray
import kotlinx.serialization.json.putJsonObject

/**
 * Generates Junie's launch-scoped hook config; user config would affect unrelated sessions and project
 * config ignores hooks. Junie interprets hook stdout and exit status, so the script stays silent, uses
 * exit 1 for permission fall-through (0 approves, 2 denies), and exits 0 for every other event even if
 * delivery fails. The secret stays in a `0600` curl header file.
 */
object JunieHookConfig {
    const val INGRESS_PATH: String = "/hooks/junie"

    const val HOOK_TOKEN_HEADER: String = "X-Kotgent-Hook-Token"

    const val TMUX_PANE_HEADER: String = "X-Kotgent-Tmux-Pane"

    const val HOOK_EVENT_HEADER: String = "X-Kotgent-Hook-Event"

    const val SHELL_INTERPRETER: String = "/bin/sh"

    /** Hooks are synchronous; an orphan-held daemon socket must not block Junie indefinitely. */
    const val CURL_MAX_TIME_SECONDS: Int = 5

    const val USER_PROMPT_SUBMIT: String = "UserPromptSubmit"
    const val PRE_TOOL_USE: String = "PreToolUse"
    const val PERMISSION_REQUEST: String = "PermissionRequest"
    const val STOP: String = "Stop"
    const val STOP_FAILURE: String = "StopFailure"
    const val SESSION_START: String = "SessionStart"
    const val SESSION_END: String = "SessionEnd"

    val HOOK_EVENTS: List<String> = listOf(
        USER_PROMPT_SUBMIT, PRE_TOOL_USE, PERMISSION_REQUEST, STOP, STOP_FAILURE, SESSION_START, SESSION_END,
    )

    private val PRETTY: Json = Json { prettyPrint = true }

    fun ingressUrl(port: Int): String = "http://127.0.0.1:$port$INGRESS_PATH"

    fun headerFileContent(token: String): String = "$HOOK_TOKEN_HEADER: $token\n"

    fun hookScript(port: Int, headerFilePath: String): String = buildString {
        appendLine("#!/bin/sh")
        appendLine("# Generated by kotgent — do not edit. Invoked by junie hooks as: <script> <EventName>")
        // Do not exec curl: Junie's control-flow exit status below must win.
        appendLine("curl -sS --max-time $CURL_MAX_TIME_SECONDS -o /dev/null -X POST \\")
        appendLine("  ${shSingleQuote(ingressUrl(port) + "?event=")}\"\$1\" \\")
        appendLine("  -H ${shSingleQuote("@$headerFilePath")} \\")
        // These values must expand when Junie invokes the hook.
        appendLine("  -H \"$TMUX_PANE_HEADER: \$TMUX_PANE\" \\")
        appendLine("  -H \"$HOOK_EVENT_HEADER: \$1\" \\")
        appendLine("  -H ${shSingleQuote("Content-Type: application/json")} \\")
        // Junie interprets any stdout as a decision or model context.
        appendLine("  --data-binary @- >/dev/null")
        appendLine("# A permission request must fall through to Junie's OWN dialog: exit 0 would")
        appendLine("# auto-approve the action and exit 2 would auto-deny it. Every other event exits 0")
        appendLine("# unconditionally — a curl failure must never disturb the session.")
        appendLine("if [ \"\$1\" = ${shSingleQuote(PERMISSION_REQUEST)} ]; then")
        appendLine("  exit 1")
        appendLine("fi")
        appendLine("exit 0")
    }

    /** Matchers are omitted because `UserPromptSubmit` and `Stop` reject them. */
    fun configJson(scriptPath: String, json: Json = PRETTY): String {
        val root = buildJsonObject {
            putJsonObject("hooks") {
                for (event in HOOK_EVENTS) {
                    putJsonArray(event) {
                        addJsonObject {
                            putJsonArray("hooks") {
                                addJsonObject {
                                    put("type", "command")
                                    put("command", hookCommand(scriptPath, event))
                                }
                            }
                        }
                    }
                }
            }
        }
        return json.encodeToString(JsonElement.serializer(), root)
    }

    fun hookCommand(scriptPath: String, event: String): String =
        "$SHELL_INTERPRETER ${shSingleQuote(scriptPath)} $event"

    private fun shSingleQuote(s: String): String = "'" + s.replace("'", "'\\''") + "'"
}
